import sys
p=sys.argv[1]; s=open(p,encoding='utf-8').read()
R={
"Fue en los felices años veinte, poco después de la Primera Guerra Mundial.":"Fue poco después de la Primera Guerra Mundial, en la época del charlestón.",
"Fue justo después del cambio de milenio.":"Fue poco después de los atentados de las Torres Gemelas.",
"Fue al comienzo del nuevo milenio.":"Fue poco después de que el euro empezara a circular.",
"Fue en los años setenta, el mismo año en que terminó la guerra de Vietnam.":"Fue el mismo año en que terminó la guerra de Vietnam.",
"Lo hizo junto a Portugal, en plena década de los ochenta.":"Lo hizo junto a Portugal, unos años después del 23-F.",
"Fue a comienzos de los sesenta, en plena Guerra Fría.":"Fue en plena Guerra Fría, el año siguiente a la crisis de los misiles de Cuba.",
"Fue a finales de los sesenta, el año de las protestas de mayo en París.":"Fue el año de las protestas estudiantiles de mayo en París.",
"Fue a comienzos de los noventa, tras casi tres décadas preso.":"Fue poco después de la caída del Muro de Berlín.",
"Se suele usar como fin de la Edad Media, unas décadas antes del viaje de Colón.":"Se suele usar como fin de la Edad Media, algo antes del viaje de Colón.",
"Fue a comienzos del siglo XIX, pocos años después de la Revolución francesa.":"Fue pocos años después de la Revolución francesa.",
"Fue la derrota definitiva de Napoleón, una década después de su coronación.":"Fue la derrota definitiva de Napoleón, unos años después de su coronación.",
"Fue a mediados de los noventa.":"Fue poco después de los Juegos Olímpicos de Barcelona.",
"Fue a finales de los felices años veinte.":"Fue justo antes del crac de la bolsa de Nueva York.",
"Fue a mediados del siglo XIX, en plena época victoriana.":"Fue en plena época victoriana, unos años antes de la guerra de Secesión estadounidense.",
"Se inauguró en la segunda mitad del siglo XIX, décadas antes que el de Panamá.":"Se inauguró mucho antes que el canal de Panamá, poco después de la guerra de Secesión.",
"Fue a comienzos de los ochenta, en una boda vista por millones de personas.":"Fue el mismo año del 23-F en España.",
"Fue a finales de los noventa, en un accidente de coche en París.":"Murió en un accidente de coche en París, el año en que se estrenó «Titanic».",
"Fue tras la abdicación de su padre, a mediados de la década pasada.":"Fue tras la abdicación de su padre, el año del Mundial de Brasil.",
"Fue el llamado «año de los tres papas».":"Fue el mismo año en que se aprobó la Constitución española.",
"Fue en los años treinta, poco antes de la Segunda Guerra Mundial.":"Fue en plena Guerra Civil española.",
"Fue a finales de los cincuenta.":"Fue poco después del lanzamiento del Sputnik.",
"Fue en los ochenta, el mismo año que el accidente de Chernóbil.":"Fue el mismo año del accidente de Chernóbil.",
"Se lanzó a comienzos de los noventa.":"Se lanzó el año en que se reunificó Alemania.",
"Se lanzó a finales de los setenta y sigue enviando datos.":"Se lanzó el mismo año en que se estrenó la primera película de Star Wars.",
"España fue uno de los primeros países del mundo en aprobarlo, a mediados de los dos mil.":"España fue uno de los primeros países en aprobarlo, el año siguiente a los atentados del 11-M.",
"Fue a comienzos de la década pasada, tras una primera ley más suave.":"Fue un año después del Mundial que ganó España en Sudáfrica.",
"Fue justo al empezar el nuevo milenio.":"Fue el mismo año de los atentados del 11-S.",
"Nació en el siglo XIX, en un periodo revolucionario.":"Nació el año de la revolución que destronó a Isabel II de España.",
"Se fundó a comienzos del siglo XVIII, con la llegada de los Borbones.":"Se fundó con la llegada de los Borbones al trono español.",
"Fue en tiempos de Felipe II, a finales del siglo XVI.":"Fue en tiempos de Felipe II y de la reina Isabel I de Inglaterra.",
"Fue apenas tres décadas después del primer viaje de Colón.":"Fue poco después de la muerte de Colón.",
"Fue en el siglo I después de Cristo, en tiempos del Imperio romano.":"Fue en tiempos del Imperio romano, poco después de la época de Jesucristo.",
"Fue en el siglo V después de Cristo.":"Fue con las invasiones de los pueblos germánicos.",
"Se le llama su «año milagroso», a comienzos del siglo XX.":"Se le llama su «año milagroso», poco después del primer vuelo de los hermanos Wright.",
"Fue a finales del siglo XVIII, contra la viruela.":"Fue contra la viruela, pocos años después de la Revolución francesa.",
"Fue a mediados de los setenta, el mismo año en que murió Franco.":"Fue el mismo año en que murió Franco.",
"Hizo escala en Canarias y la travesía duró más de dos meses.":"Hizo escala en Canarias y la travesía duró varias semanas.",
"Salieron varios cientos y regresaron muy pocos.":"Salieron muchísimos más y regresaron muy pocos.",
"Era algo más de cien y tenía tres decimales.":"Un euro valía bastante más que un billete verde de cien pesetas; además tenía decimales.",
"Como sus mandatos no fueron seguidos, cuenta dos veces.":"Como sus mandatos no fueron seguidos, se le cuenta por separado en cada uno.",
"Gobernó a mediados del siglo XIX.":"Gobernó durante la guerra de Secesión.",
"Son bastantes más de cien.":"Es un texto largo, con títulos y disposiciones al final.",
}
for a,b in R.items():
    n=s.count(a); assert n>=1,a; s=s.replace(a,b)
open(p,'w',encoding='utf-8').write(s)
