// Fuentes citadas al revelar cada respuesta.
const SOURCES={
  takeTwo:{name:'Take-Two Interactive — notas de prensa',url:'https://ir.take2games.com/'},
  rockstar:{name:'Rockstar Games — Newswire',url:'https://www.rockstargames.com/newswire'},
  guinness:{name:'Guinness World Records',url:'https://www.guinnessworldrecords.com/'},
  nintendo:{name:'Nintendo — datos de ventas oficiales',url:'https://www.nintendo.co.jp/ir/en/finance/hard_soft/index.html'},
  nintendoHist:{name:'Nintendo — historia de la compañía',url:'https://www.nintendo.com/'},
  sony:{name:'Sony Interactive Entertainment',url:'https://sonyinteractive.com/en/our-company/business-data-sales/'},
  xbox:{name:'Xbox Wire / Microsoft',url:'https://news.xbox.com/'},
  microsoft:{name:'Microsoft — notas de prensa',url:'https://news.microsoft.com/'},
  epic:{name:'Epic Games',url:'https://www.epicgames.com/'},
  britannica:{name:'Encyclopaedia Britannica',url:'https://www.britannica.com/'},
  nasa:{name:'NASA',url:'https://www.nasa.gov/'},
  apollo:{name:'NASA — Apollo 11',url:'https://www.nasa.gov/mission/apollo-11/'},
  esa:{name:'ESA — Agencia Espacial Europea',url:'https://www.esa.int/'},
  boxoffice:{name:'Box Office Mojo',url:'https://www.boxofficemojo.com/'},
  oscars:{name:'Academia de Hollywood — base de datos de los Óscar',url:'https://awardsdatabase.oscars.org/'},
  imdb:{name:'IMDb',url:'https://www.imdb.com/'},
  billboard:{name:'Billboard',url:'https://www.billboard.com/'},
  grammy:{name:'Recording Academy — Grammy',url:'https://www.grammy.com/'},
  eurovision:{name:'Eurovision Song Contest — sitio oficial',url:'https://eurovision.tv/'},
  youtube:{name:'YouTube — «Me at the zoo»',url:'https://www.youtube.com/watch?v=jNQXAC9IVRw'},
  spotify:{name:'Spotify — Newsroom',url:'https://newsroom.spotify.com/'},
  netflix:{name:'Netflix — About / Tudum',url:'https://about.netflix.com/'},
  disney:{name:'The Walt Disney Company',url:'https://thewaltdisneycompany.com/'},
  apple:{name:'Apple Newsroom',url:'https://www.apple.com/newsroom/'},
  meta:{name:'Meta Newsroom',url:'https://about.fb.com/news/'},
  google:{name:'Google — Nuestra historia',url:'https://about.google/'},
  sec:{name:'SEC — documentos oficiales de la operación',url:'https://www.sec.gov/'},
  nokia:{name:'Nokia',url:'https://www.nokia.com/'},
  motorola:{name:'Motorola Solutions — historia',url:'https://www.motorolasolutions.com/en_us/about/company-overview/history.html'},
  chm:{name:'Computer History Museum',url:'https://www.computerhistory.org/'},
  cern:{name:'CERN — El nacimiento de la web',url:'https://home.cern/science/computing/birth-web'},
  wikimedia:{name:'Wikimedia Foundation',url:'https://wikimediafoundation.org/'},
  openai:{name:'OpenAI',url:'https://openai.com/'},
  fifa:{name:'FIFA',url:'https://www.fifa.com/'},
  uefa:{name:'UEFA',url:'https://www.uefa.com/'},
  laliga:{name:'LaLiga',url:'https://www.laliga.com/'},
  rfef:{name:'Real Federación Española de Fútbol',url:'https://rfef.es/'},
  olympics:{name:'Olympics.com',url:'https://www.olympics.com/'},
  athletics:{name:'World Athletics — récords',url:'https://worldathletics.org/records/by-category/world-records'},
  atp:{name:'ATP Tour / WTA',url:'https://www.atptour.com/'},
  itf:{name:'ITF — reglamento y Copa Davis',url:'https://www.itftennis.com/'},
  wimbledon:{name:'Wimbledon — sitio oficial',url:'https://www.wimbledon.com/'},
  rg:{name:'Roland-Garros — sitio oficial',url:'https://www.rolandgarros.com/'},
  nba:{name:'NBA.com',url:'https://www.nba.com/'},
  fiba:{name:'FIBA',url:'https://www.fiba.basketball/'},
  feb:{name:'Federación Española de Baloncesto',url:'https://www.feb.es/'},
  f1:{name:'Formula 1 — sitio oficial',url:'https://www.formula1.com/'},
  motogp:{name:'MotoGP — sitio oficial',url:'https://www.motogp.com/'},
  letour:{name:'Tour de France — sitio oficial',url:'https://www.letour.fr/'},
  ballon:{name:'France Football — Balón de Oro',url:'https://www.francefootball.fr/'},
  fcb:{name:'FC Barcelona — sitio oficial',url:'https://www.fcbarcelona.es/'},
  rm:{name:'Real Madrid — sitio oficial',url:'https://www.realmadrid.com/'},
  nfl:{name:'NFL',url:'https://www.nfl.com/'},
  pga:{name:'PGA Tour / Augusta National',url:'https://www.masters.com/'},
  coe:{name:'Comité Olímpico Español',url:'https://www.coe.es/'},
  eiffel:{name:'Torre Eiffel — sitio oficial',url:'https://www.toureiffel.paris/es'},
  burj:{name:'Burj Khalifa — sitio oficial',url:'https://www.burjkhalifa.ae/'},
  nps:{name:'National Park Service — Estatua de la Libertad',url:'https://www.nps.gov/stli/'},
  esb:{name:'Empire State Building — sitio oficial',url:'https://www.esbnyc.com/'},
  ggb:{name:'Golden Gate Bridge — sitio oficial',url:'https://www.goldengate.org/'},
  parliament:{name:'UK Parliament — Big Ben',url:'https://www.parliament.uk/bigben'},
  louvre:{name:'Museo del Louvre',url:'https://www.louvre.fr/'},
  reinasofia:{name:'Museo Reina Sofía — Guernica',url:'https://www.museoreinasofia.es/coleccion/obra/guernica'},
  prado:{name:'Museo del Prado',url:'https://www.museodelprado.es/'},
  christies:{name:"Christie's / Sotheby's",url:'https://www.christies.com/'},
  unesco:{name:'UNESCO — Patrimonio Mundial',url:'https://whc.unesco.org/'},
  sagrada:{name:'Basílica de la Sagrada Familia — sitio oficial',url:'https://sagradafamilia.org/'},
  bne:{name:'Biblioteca Nacional de España',url:'https://www.bne.es/'},
  rae:{name:'Real Academia Española',url:'https://www.rae.es/'},
  bde:{name:'Banco de España',url:'https://www.bde.es/'},
  congreso:{name:'Congreso de los Diputados',url:'https://www.congreso.es/'},
  casareal:{name:'Casa de S.M. el Rey',url:'https://www.casareal.es/'},
  vatican:{name:'Santa Sede — Vatican.va',url:'https://www.vatican.va/'},
  whitehouse:{name:'The White House — Presidentes',url:'https://www.whitehouse.gov/about-the-white-house/presidents/'},
  royal:{name:'The Royal Family',url:'https://www.royal.uk/'},
  un:{name:'Naciones Unidas',url:'https://www.un.org/es/'},
  who:{name:'Organización Mundial de la Salud',url:'https://www.who.int/es'},
  eu:{name:'Unión Europea — sitio oficial',url:'https://european-union.europa.eu/'},
  ine:{name:'INE — Instituto Nacional de Estadística',url:'https://www.ine.es/'},
  ign:{name:'Instituto Geográfico Nacional',url:'https://www.ign.es/'},
  nobel:{name:'NobelPrize.org',url:'https://www.nobelprize.org/'},
  cocacola:{name:'The Coca-Cola Company — historia',url:'https://www.coca-colacompany.com/about-us/history'},
  lego:{name:'The LEGO Group — historia',url:'https://www.lego.com/es-es/aboutus/lego-group/the-lego-group-history'},
  ikea:{name:'IKEA — historia',url:'https://about.ikea.com/'},
  inditex:{name:'Inditex — historia',url:'https://www.inditex.com/'},
  mercadona:{name:'Mercadona — historia',url:'https://info.mercadona.es/'},
  ferrero:{name:'Ferrero — historia de sus marcas',url:'https://www.ferrero.com/'},
  mattel:{name:'Mattel',url:'https://corporate.mattel.com/'},
  hasbro:{name:'Hasbro',url:'https://corporate.hasbro.com/'},
  chupachups:{name:'Chupa Chups — historia',url:'https://www.chupachups.es/'},
  mcdonalds:{name:"McDonald's — historia",url:'https://corporate.mcdonalds.com/'},
  ford:{name:'Ford Motor Company — historia',url:'https://corporate.ford.com/'},
  vw:{name:'Volkswagen — historia',url:'https://www.volkswagen-newsroom.com/'},
  company:{name:'Historia oficial de la marca (sitio corporativo)',url:'https://www.britannica.com/topic/business'},
  pollstar:{name:'Pollstar / Billboard Boxscore',url:'https://news.pollstar.com/'},
  shueisha:{name:'Shueisha / Guinness World Records',url:'https://www.guinnessworldrecords.com/'},
  marvel:{name:'Marvel / DC — historia editorial',url:'https://www.marvel.com/'},
  smithsonian:{name:'Smithsonian Institution',url:'https://www.si.edu/'},
  nhm:{name:'Natural History Museum',url:'https://www.nhm.ac.uk/'},
  nih:{name:'NIH / MedlinePlus',url:'https://medlineplus.gov/'},
  nepal:{name:'Gobiernos de Nepal y China — medición de 2020',url:'https://www.britannica.com/place/Mount-Everest'},
  aquatics:{name:'World Aquatics — reglamento de instalaciones',url:'https://www.worldaquatics.com/'},
  rules:{name:'Reglamento oficial del juego o deporte',url:'https://www.britannica.com/'},
  rtve:{name:'RTVE — archivo',url:'https://www.rtve.es/'},
  metro:{name:'Historia oficial de la red de transporte',url:'https://www.britannica.com/technology/subway'},
  adif:{name:'Adif / Renfe — historia de la alta velocidad',url:'https://www.adif.es/'}
};

const RAW=[];
// Pregunta de cifra: N(texto, respuesta, unidad, pista, opciones)
// opciones: s = fuente, ap = cifra aproximada, d = decimales, n = nota al revelar
function N(t,a,u,h,o={}){return {t,a,u,h,...o};}
// Pregunta de año: Y(texto, año, pista, opciones)
function Y(t,a,h,o={}){return {t,a,u:'',y:true,h,...o};}
function add(cat,src,list){for(const x of list)RAW.push({...x,cat,s:x.s||src});}
