add('Cine','britannica',[
  // ── Años de estreno ──
  Y('¿En qué año se estrenó la película «Titanic» de James Cameron?',1997,'Se estrenó el mismo año en que murió Diana de Gales.'),
  Y('¿En qué año se estrenó «Jurassic Park»?',1993,'Se estrenó un año después de los Juegos Olímpicos de Barcelona.'),
  Y('¿En qué año se estrenó «E.T., el extraterrestre»?',1982,'Se estrenó el año del Mundial de España.'),
  Y('¿En qué año se estrenó «Tiburón» de Spielberg?',1975,'Se estrenó el año en que murió Franco.'),
  Y('¿En qué año se estrenó «El Padrino»?',1972,'Se estrenó unos años después de la llegada del hombre a la Luna.'),
  Y('¿En qué año se estrenó la primera película de Star Wars?',1977,'Se estrenó el mismo año en que murió Elvis Presley.'),
  Y('¿En qué año se estrenó «Regreso al futuro»?',1985,'Se estrenó el año de «Live Aid», el gran concierto benéfico de Queen.'),
  Y('¿En qué año se estrenó «Matrix»?',1999,'Se estrenó el mismo año que «Star Wars: La amenaza fantasma».'),
  Y('¿En qué año se estrenó «Forrest Gump»?',1994,'Se estrenó el mismo año que «El Rey León».'),
  Y('¿En qué año se estrenó «El Rey León» de dibujos animados?',1994,'Se estrenó el mismo año que «Forrest Gump».',{s:'disney'}),
  Y('¿En qué año se estrenó «Pulp Fiction»?',1994,'Ganó la Palma de Oro el mismo año en que se estrenó «Forrest Gump».'),
  Y('¿En qué año se estrenó «Toy Story», la primera película hecha totalmente por ordenador?',1995,'Se estrenó al año siguiente de «El Rey León».'),
  Y('¿En qué año se estrenó «Shrek»?',2001,'Se estrenó el mismo año que la primera película de Harry Potter.'),
  Y('¿En qué año se estrenó la primera película de Harry Potter?',2001,'Se estrenó el mismo año que «Shrek» y «Monstruos, S.A.».'),
  Y('¿En qué año se estrenó «El Señor de los Anillos: La Comunidad del Anillo»?',2001,'Se estrenó en Navidad, unos meses después del 11-S.'),
  Y('¿En qué año se estrenó la primera película de «Piratas del Caribe»?',2003,'Se estrenó el mismo año que «Buscando a Nemo».'),
  Y('¿En qué año se estrenó «Buscando a Nemo»?',2003,'Se estrenó el mismo año que la primera de «Piratas del Caribe».'),
  Y('¿En qué año se estrenó «Avatar»?',2009,'Se estrenó un año después de la quiebra de Lehman Brothers.'),
  Y('¿En qué año se estrenó «Frozen: El reino del hielo»?',2013,'Se estrenó el año en que fue elegido el papa Francisco.',{s:'disney'}),
  Y('¿En qué año se estrenó «Los Vengadores», la primera que los reunió a todos?',2012,'Se estrenó el año de los Juegos Olímpicos de Londres.'),
  Y('¿En qué año se estrenó la primera película de «Iron Man»?',2008,'Se estrenó el mismo año que «El caballero oscuro».'),
  Y('¿En qué año se estrenó «El caballero oscuro» con Heath Ledger como Joker?',2008,'Se estrenó unos meses después de la muerte de Heath Ledger.'),
  Y('¿En qué año se estrenó «Gladiator»?',2000,'Se estrenó justo con el cambio de siglo.'),
  Y('¿En qué año se estrenó «Psicosis» de Hitchcock?',1960,'Se estrenó cuando los Beatles todavía no eran famosos.'),
  Y('¿En qué año se estrenó «Lo que el viento se llevó»?',1939,'Se estrenó el año en que empezó la Segunda Guerra Mundial.'),
  Y('¿En qué año se estrenó «El mago de Oz» con Judy Garland?',1939,'Se estrenó el mismo año que «Lo que el viento se llevó».'),
  Y('¿En qué año se estrenó «Blancanieves y los siete enanitos» de Disney?',1937,'Fue el primer largometraje de Disney, poco antes de la Segunda Guerra Mundial.',{s:'disney'}),
  Y('¿En qué año se estrenó «Casablanca»?',1942,'Se estrenó en plena Segunda Guerra Mundial.'),
  Y('¿En qué año se estrenó la primera película de «Rocky»?',1976,'Se estrenó el año del bicentenario de Estados Unidos.'),
  Y('¿En qué año se estrenó «Grease»?',1978,'Se estrenó el año en que se aprobó la Constitución española.'),
  Y('¿En qué año se estrenó «Dirty Dancing»?',1987,'Se estrenó poco antes de la caída del Muro de Berlín.'),
  Y('¿En qué año se estrenó «Pretty Woman»?',1990,'Se estrenó el año de la reunificación alemana.'),
  Y('¿En qué año se estrenó «Solo en casa»?',1990,'Se estrenó el mismo año que «Pretty Woman».'),
  Y('¿En qué año se estrenó «En busca del arca perdida», la primera de Indiana Jones?',1981,'Se estrenó el mismo año del 23-F.'),
  Y('¿En qué año se estrenó «Terminator»?',1984,'Se estrenó el mismo año que «Los Cazafantasmas».'),
  Y('¿En qué año se estrenó «Los Cazafantasmas»?',1984,'Se estrenó el mismo año que «Terminator».'),
  Y('¿En qué año se estrenó «Top Gun» con Tom Cruise?',1986,'Se estrenó el año del accidente de Chernóbil.'),
  Y('¿En qué año se estrenó «Scream»?',1996,'Se estrenó el año en que nació la oveja Dolly.'),
  Y('¿En qué año se estrenó «Men in Black»?',1997,'Se estrenó el mismo año que «Titanic».'),
  Y('¿En qué año se estrenó «Up» de Pixar?',2009,'Se estrenó el mismo año que «Avatar».'),
  Y('¿En qué año se estrenó «Coco» de Pixar?',2017,'Se estrenó el año en que salió la Nintendo Switch.'),
  Y('¿En qué año se estrenó «Joker» con Joaquin Phoenix?',2019,'Se estrenó justo antes de la pandemia.'),
  Y('¿En qué año se estrenaron «Barbie» y «Oppenheimer», el fenómeno «Barbenheimer»?',2023,'Se estrenaron hace muy poco, el mismo fin de semana.'),
  Y('¿En qué año se estrenó «Interstellar»?',2014,'Se estrenó el año en que fue proclamado rey Felipe VI.'),
  Y('¿En qué año se estrenó «Origen» (Inception)?',2010,'Se estrenó el año en que España ganó el Mundial.'),
  Y('¿En qué año se estrenó «La La Land»?',2016,'Se estrenó el año del referéndum del Brexit.'),
  Y('¿En qué año se estrenó el «Spider-Man» de Sam Raimi con Tobey Maguire?',2002,'Se estrenó el año en que llegó el euro a los bolsillos.'),
  Y('¿En qué año se estrenó «La sirenita» de Disney?',1989,'Se estrenó el año de la caída del Muro de Berlín.',{s:'disney'}),
  Y('¿En qué año se estrenó «Aladdín» de dibujos animados?',1992,'Se estrenó el año de la Expo de Sevilla.',{s:'disney'}),
  Y('¿En qué año se estrenó «La bella y la bestia» de dibujos animados?',1991,'Se estrenó el año en que se disolvió la Unión Soviética.',{s:'disney'}),
  Y('¿En qué año se estrenó «Mulan» de dibujos animados?',1998,'Se estrenó el año del Mundial de Francia.',{s:'disney'}),
  Y('¿En qué año se estrenó «Los Increíbles»?',2004,'Se estrenó el mismo año que la segunda de Shrek y que los atentados del 11-M.'),
  Y('¿En qué año se estrenó «Cars»?',2006,'Se estrenó el año en que salió la Wii.'),
  Y('¿En qué año se estrenó «Ratatouille»?',2007,'Se estrenó el año en que se presentó el primer iPhone.'),
  Y('¿En qué año se estrenó «Del revés» (Inside Out)?',2015,'Se estrenó el mismo año que «Minions».'),
  Y('¿En qué año se estrenó «Gru, mi villano favorito»?',2010,'Se estrenó el año en que España ganó el Mundial.'),
  Y('¿En qué año se estrenó «Kung Fu Panda»?',2008,'Se estrenó el año de los Juegos Olímpicos de Pekín.'),
  Y('¿En qué año se estrenó «Ice Age: La edad de hielo»?',2002,'Se estrenó el año en que llegó el euro.'),
  Y('¿En qué año se estrenó la primera «Fast & Furious»?',2001,'Se estrenó el mismo año que la primera de Harry Potter.'),
  Y('¿En qué año se estrenó «El laberinto del fauno» de Guillermo del Toro?',2006,'Se estrenó el mismo año que «Volver» de Almodóvar.'),
  Y('¿En qué año se estrenó «Ocho apellidos vascos»?',2014,'Se estrenó el año en que fue proclamado rey Felipe VI.'),
  Y('¿En qué año se estrenó la primera película de «Torrente»?',1998,'Se estrenó el mismo año que «Mulan».'),
  Y('¿En qué año se estrenó «Lo imposible» de J. A. Bayona?',2012,'Se estrenó el año de los Juegos de Londres.'),
  Y('¿En qué año se estrenó «Campeones» de Javier Fesser?',2018,'Se estrenó el año en que España jugó el Mundial de Rusia.'),
  Y('¿En qué año se hizo la primera proyección de cine de los hermanos Lumière?',1895,'Fue en un café de París, antes de que existieran los aviones.'),
  Y('¿En qué año se celebró la primera gala de los Óscar?',1929,'Fue el mismo año del crac de la bolsa de Nueva York.',{s:'oscars'}),
  Y('¿En qué año se estrenó «El cantor de jazz», la primera película sonora?',1927,'Fue poco antes de la primera gala de los Óscar.'),
  Y('¿En qué año se instaló el famoso letrero de Hollywood?',1923,'Se instaló en plena época del cine mudo.'),

  // ── Óscar ──
  N('¿Cuántos premios Óscar ganó la película «Titanic»?',11,'Óscar','Igualó el récord histórico de premios.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «El Señor de los Anillos: El retorno del rey»?',11,'Óscar','Ganó en todas las categorías a las que estaba nominada.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «Ben-Hur»?',11,'Óscar','Fue la primera en conseguir un récord que luego igualaron «Titanic» y «El retorno del rey».',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «Lo que el viento se llevó»?',8,'Óscar','Fue un récord en su época.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «Oppenheimer»?',7,'Óscar','Arrasó, incluida mejor película y mejor director.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «La La Land»?',6,'Óscar','Ganó muchos, pero no el de mejor película, tras un error histórico en el sobre.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «Forrest Gump»?',6,'Óscar','Ganó mejor película y mejor actor para Tom Hanks.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «Parásitos»?',4,'Óscar','Fue la primera película de habla no inglesa en ganar el de mejor película.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «Gladiator»?',5,'Óscar','Ganó mejor película y mejor actor para Russell Crowe.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «La lista de Schindler»?',7,'Óscar','Le dio a Spielberg su primer Óscar como director.',{s:'oscars'}),
  N('¿Cuántos premios Óscar ganó «Bohemian Rhapsody»?',4,'Óscar','Uno de ellos fue para Rami Malek como Freddie Mercury.',{s:'oscars'}),
  N('¿Cuántas nominaciones al Óscar recibió «La La Land», igualando el récord?',14,'nominaciones','Comparte el récord con «Titanic» y «Eva al desnudo».',{s:'oscars'}),
  N('¿Cuántas veces ha sido nominada Meryl Streep al Óscar?',21,'nominaciones','Es la intérprete con más nominaciones de la historia.',{s:'oscars'}),
  N('¿Cuántos Óscar ha ganado Meryl Streep?',3,'Óscar','Ha ganado muchísimos menos de los que ha optado.',{s:'oscars'}),
  N('¿Cuántos Óscar de interpretación ganó Katharine Hepburn, récord absoluto?',4,'Óscar','Nadie ha ganado más premios como intérprete.',{s:'oscars'}),
  N('¿Cuántos Óscar a mejor actor ganó Daniel Day-Lewis, récord en esa categoría?',3,'Óscar','Es el único actor que lo ha conseguido tantas veces.',{s:'oscars'}),
  N('¿Cuántos Óscar ha ganado Pedro Almodóvar?',2,'Óscar','Uno fue por «Todo sobre mi madre».',{s:'oscars'}),
  N('¿Cuántas películas españolas han ganado el Óscar a mejor película internacional?',4,'películas','La última fue «Mar adentro».',{s:'oscars'}),
  N('¿Cuántos premios Óscar competitivos ganó Walt Disney, récord absoluto para una persona?',22,'Óscar','Nadie ha ganado tantos como él.',{s:'guinness'}),
  N('¿Cuántas nominaciones al Óscar recibió Walt Disney a lo largo de su vida?',59,'nominaciones','Es el récord absoluto de nominaciones para una persona.',{s:'guinness'}),
  N('¿Cuántos centímetros mide la estatuilla de los Óscar?',34,'cm','Es más pequeña de lo que parece en televisión.',{s:'oscars',ap:true}),
  N('¿Cuántos metros de alto mide cada letra del letrero de Hollywood?',14,'m','Cada letra es más alta que un edificio de varios pisos.',{ap:true}),

  // ── Duración ──
  N('¿Cuántos minutos dura la película «Titanic» de James Cameron?',194,'minutos','Es más larga que una final de Champions con prórroga y penaltis.'),
  N('¿Cuántos minutos dura «El Señor de los Anillos: El retorno del rey» en cines?',201,'minutos','Es la más larga de la trilogía en su versión de cine.'),
  N('¿Cuántos minutos dura «Vengadores: Endgame»?',181,'minutos','Es la más larga de todas las películas de Marvel.'),
  N('¿Cuántos minutos dura «El Padrino»?',175,'minutos','Es muy larga, aunque menos que su segunda parte.'),
  N('¿Cuántos minutos dura «Oppenheimer»?',180,'minutos','Es una de las películas más largas en ganar el Óscar a mejor película en los últimos tiempos.'),
  N('¿Cuántos minutos dura «Avatar» (la primera)?',162,'minutos','Es larga, pero bastante más corta que «Titanic».'),
  N('¿Cuántos minutos dura «Toy Story»?',81,'minutos','Es bastante corta, como muchas películas de animación de la época.'),
  N('¿Cuántos minutos dura «El Rey León» de dibujos animados?',88,'minutos','Es una película corta, de menos de hora y media.',{s:'disney'}),
  N('¿Cuántos minutos dura «Interstellar»?',169,'minutos','Es una de las películas más largas de Christopher Nolan.'),
  N('¿Cuántos minutos dura «Joker» con Joaquin Phoenix?',122,'minutos','Tiene una duración normal para una película de cine adulto.'),
  N('¿Cuántos minutos dura «Barbie»?',114,'minutos','Dura menos que la mayoría de grandes estrenos de su año.'),
  N('¿Cuántos minutos dura «Shrek»?',90,'minutos','Dura lo mismo que un partido de fútbol sin descanso.'),
  N('¿Cuántos minutos dura «Frozen: El reino del hielo»?',102,'minutos','Dura algo más de hora y media.',{s:'disney'}),
  N('¿Cuántos minutos dura «Matrix»?',136,'minutos','Es más larga que una película de animación, pero no excesivamente.'),
  N('¿Cuántos minutos dura «Pulp Fiction»?',154,'minutos','Es la más larga de Tarantino de su época, con historias cruzadas.'),
  N('¿Cuántos minutos dura «Forrest Gump»?',142,'minutos','Es más larga que una película de animación, pero no excesivamente.'),
  N('¿Cuántos minutos dura «Jurassic Park»?',127,'minutos','Tiene una duración normal para una película de cine adulto.'),

  // ── Taquilla y presupuestos ──
  N('¿Cuántos millones de dólares ha recaudado «Avatar», la película más taquillera de la historia?',2923,'millones $','Ninguna película ha recaudado más.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Vengadores: Endgame» en todo el mundo?',2799,'millones $','Es la segunda más taquillera de la historia.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares ha recaudado «Avatar: El sentido del agua»?',2320,'millones $','Está entre las más taquilleras de la historia, pero por debajo de la primera.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares ha recaudado «Titanic» contando sus reestrenos?',2264,'millones $','Fue la más taquillera de la historia hasta que llegó «Avatar».',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Star Wars: El despertar de la Fuerza»?',2068,'millones $','Es la película de Star Wars más taquillera.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Vengadores: Infinity War»?',2052,'millones $','Recaudó un poco menos que su continuación.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Jurassic World»?',1671,'millones $','Recaudó muchísimo más que la «Jurassic Park» original.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Del revés 2»?',1699,'millones $','Es una de las películas de animación más taquilleras de la historia.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Top Gun: Maverick»?',1496,'millones $','Fue la más taquillera del año de su estreno en muchos países.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Super Mario Bros.: La película»?',1361,'millones $','Es la adaptación de videojuego más taquillera.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Barbie»?',1446,'millones $','Fue la película más taquillera del año del «Barbenheimer».',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Oppenheimer»?',975,'millones $','Recaudó bastante menos que «Barbie», pero muchísimo para un drama histórico.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Joker» con Joaquin Phoenix?',1079,'millones $','Fue la primera película para mayores de edad en superar cierta barrera redonda.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares recaudó «Minions»?',1159,'millones $','Recaudó más que la primera de «Gru».',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares costó rodar «Titanic»?',200,'millones $','Fue la película más cara de la historia en su momento.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares costó rodar «Avatar» (la primera)?',237,'millones $','Costó algo más que «Titanic», del mismo director.',{s:'boxoffice',ap:true}),
  N('¿Cuántos millones de dólares pagó Disney por Lucasfilm (Star Wars)?',4050,'millones $','Fue la misma cantidad aproximada que pagó por Marvel… algo más.',{s:'disney',ap:true}),
  N('¿Cuántos millones de dólares pagó Disney por Marvel?',4000,'millones $','Fue una cifra redonda.',{s:'disney',ap:true}),
  N('¿Cuántos millones de dólares pagó Disney por Pixar?',7400,'millones $','Pagó bastante más que por Marvel o Lucasfilm.',{s:'disney',ap:true}),

  // ── Sagas y curiosidades ──
  N('¿Cuántas películas oficiales de James Bond ha producido Eon Productions hasta «Sin tiempo para morir»?',25,'películas','Llevan haciéndolas desde los tiempos de Sean Connery.'),
  N('¿Cuántos actores han interpretado a James Bond en las películas oficiales?',6,'actores','El último fue Daniel Craig.'),
  N('¿Cuántas películas tiene la saga «Rocky», sin contar las de «Creed»?',6,'películas','La última se estrenó muchos años después de la primera.'),
  N('¿Cuántas películas tiene la saga principal de Harry Potter, sin contar «Animales fantásticos»?',8,'películas','Hay más películas que libros, porque el último se partió.'),
  N('¿Cuántos episodios tiene la saga principal de Star Wars (la «Saga Skywalker»)?',9,'episodios','Son varias trilogías rodadas a lo largo de muchos años.'),
  N('¿Cuántos anillos de poder se forjaron en total en «El Señor de los Anillos», contando el Anillo Único?',20,'anillos','Hay anillos para elfos, enanos, hombres… y uno para gobernarlos a todos.'),
  N('¿Cuántos dedos tiene en cada mano un personaje de «Los Simpson»?',4,'dedos','Les falta uno respecto a nosotros.'),
  N('¿Cuántos años tiene Bart Simpson?',10,'años','Va a la escuela primaria y no crece nunca.'),
  N('¿Cuántos años tiene Lisa Simpson?',8,'años','Es más pequeña que Bart.')
]);
