add('Series y TV','imdb',[
  // ── Episodios y temporadas ──
  N('¿Cuántos episodios tiene «Friends»?',236,'episodios','Duró muchos años en antena con temporadas largas, de las de antes.'),
  N('¿Cuántas temporadas tiene «Friends»?',10,'temporadas','Acabó cuando Rachel se iba a vivir a París… o casi.'),
  N('¿Cuántos episodios tiene «Breaking Bad»?',62,'episodios','Tiene pocas temporadas y bastante cortas.'),
  N('¿Cuántas temporadas tiene «Breaking Bad»?',5,'temporadas','La última se emitió partida, con un parón en medio.'),
  N('¿Cuántos episodios tiene «Juego de Tronos»?',73,'episodios','Las últimas temporadas tuvieron menos capítulos que las primeras.'),
  N('¿Cuántas temporadas tiene «Juego de Tronos»?',8,'temporadas','Terminó antes de que se publicaran los libros que faltaban.'),
  N('¿Cuántos episodios tiene «Los Soprano»?',86,'episodios','Fue una serie de cable con temporadas cortas.'),
  N('¿Cuántos episodios tiene «The Office» (versión estadounidense)?',201,'episodios','Duró bastantes temporadas en abierto.'),
  N('¿Cuántos episodios tiene «Cómo conocí a vuestra madre»?',208,'episodios','Tardaron muchísimo en contar cómo conoció a la madre.'),
  N('¿Cuántas temporadas tiene «Cómo conocí a vuestra madre»?',9,'temporadas','Se quedó a una de llegar a la cifra redonda de «Friends».'),
  N('¿Cuántos episodios tiene «The Big Bang Theory»?',279,'episodios','Es una de las comedias de más larga duración de su época.'),
  N('¿Cuántas temporadas tiene «The Big Bang Theory»?',12,'temporadas','Superó en temporadas a «Friends».'),
  N('¿Cuántos episodios tiene «Perdidos» (Lost)?',121,'episodios','Tuvo temporadas largas al principio y más cortas al final.'),
  N('¿Cuántos episodios tiene «Dexter» (la serie original)?',96,'episodios','Fue una serie de cable con temporadas cortas.'),
  N('¿Cuántos episodios tiene «Seinfeld»?',180,'episodios','Fue una de las comedias más vistas de su época en Estados Unidos.'),
  N('¿Cuántos episodios tiene «Mad Men»?',92,'episodios','Fue una serie de cable con temporadas cortas.'),
  N('¿Cuántos episodios tiene «The Walking Dead» (la serie original)?',177,'episodios','Duró muchas temporadas con capítulos abundantes.'),
  N('¿Cuántos episodios tiene «Better Call Saul»?',63,'episodios','Tiene casi los mismos capítulos que «Breaking Bad».'),
  N('¿Cuántos episodios tiene «Stranger Things» en total?',42,'episodios','Sus temporadas son cortas y tardaban mucho en estrenarse.',{s:'netflix'}),
  N('¿Cuántos episodios tiene «Dragon Ball Z»?',291,'episodios','Es mucho más larga que la «Dragon Ball» original.'),
  N('¿Cuántos episodios tiene la «Dragon Ball» original?',153,'episodios','Es bastante más corta que «Dragon Ball Z».'),
  N('¿Cuántos episodios tiene la serie original de «Naruto» (sin contar «Shippuden»)?',220,'episodios','Es la parte que cuenta su infancia; la continuación es aún más larga.'),
  N('¿Cuántos episodios tiene «Naruto Shippuden»?',500,'episodios','Es una cifra muy redonda y muy alta.'),
  N('¿Cuántos episodios tiene la serie original de «Los Caballeros del Zodiaco»?',114,'episodios','Es más corta que «Dragon Ball».'),
  N('¿Cuántos episodios tiene la serie original de «Oliver y Benji» (Captain Tsubasa)?',128,'episodios','Los partidos duraban varios capítulos y el campo parecía infinito.'),

  // ── Años de estreno ──
  Y('¿En qué año se estrenó «Los Simpson» como serie propia?',1989,'Se estrenó el año de la caída del Muro de Berlín.'),
  Y('¿En qué año se estrenó «Friends»?',1994,'Se estrenó el mismo año que «El Rey León».'),
  Y('¿En qué año se estrenó «Seinfeld»?',1989,'Se estrenó el mismo año que «Los Simpson».'),
  Y('¿En qué año se estrenó «Breaking Bad»?',2008,'Se estrenó el año de la quiebra de Lehman Brothers.'),
  Y('¿En qué año se estrenó «Juego de Tronos»?',2011,'Se estrenó un año después de que España ganara el Mundial.'),
  Y('¿En qué año se estrenó «Stranger Things»?',2016,'Se estrenó el año del referéndum del Brexit, aunque la serie es de ambientación retro.',{s:'netflix'}),
  Y('¿En qué año se estrenó «Los Soprano»?',1999,'Se estrenó el mismo año que «Matrix».'),
  Y('¿En qué año se estrenó «Perdidos» (Lost)?',2004,'Se estrenó el mismo año que se fundó Facebook.'),
  Y('¿En qué año se estrenó «The Big Bang Theory»?',2007,'Se estrenó el año en que se presentó el primer iPhone.'),
  Y('¿En qué año se estrenó «The Walking Dead»?',2010,'Se estrenó el año en que España ganó el Mundial.'),
  Y('¿En qué año se estrenó «Black Mirror»?',2011,'Se estrenó el mismo año que «Juego de Tronos».'),
  Y('¿En qué año se estrenó «La casa de papel»?',2017,'Se estrenó en televisión en abierto antes de saltar a Netflix, el año de la Nintendo Switch.',{s:'netflix'}),
  Y('¿En qué año se estrenó «Élite»?',2018,'Se estrenó un año después que «La casa de papel».',{s:'netflix'}),
  Y('¿En qué año se estrenó «El juego del calamar»?',2021,'Se estrenó cuando aún coleaba la pandemia.',{s:'netflix'}),
  Y('¿En qué año se estrenó «Miércoles» (Wednesday)?',2022,'Se estrenó el año del Mundial de Catar.',{s:'netflix'}),
  Y('¿En qué año se emitió la primera edición de «Operación Triunfo»?',2001,'Se emitió el mismo año de los atentados del 11-S.',{s:'rtve'}),
  Y('¿En qué año se emitió el primer «Gran Hermano» en España?',2000,'Se emitió justo con el cambio de siglo.'),
  Y('¿En qué año se estrenó «Los Serrano»?',2003,'Se estrenó el mismo año que «Aquí no hay quien viva».'),
  Y('¿En qué año se estrenó «Aquí no hay quien viva»?',2003,'Se estrenó el mismo año que «Los Serrano».'),
  Y('¿En qué año se estrenó «Cuéntame cómo pasó»?',2001,'Se estrenó el mismo año que «Operación Triunfo».',{s:'rtve'}),
  Y('¿En qué año se estrenó «Médico de familia»?',1995,'Se estrenó el mismo año que «Toy Story».'),
  Y('¿En qué año se estrenó «Verano azul»?',1981,'Se estrenó el año del 23-F.',{s:'rtve'}),
  Y('¿En qué año se estrenó «El Hormiguero»?',2006,'Se estrenó el mismo año que salió la Wii.'),
  Y('¿En qué año empezó «Pasapalabra» en España?',2000,'Empezó el mismo año que el primer «Gran Hermano».'),
  Y('¿En qué año empezó «Saber y ganar»?',1997,'Empezó el año de «Titanic».',{s:'rtve'}),
  Y('¿En qué año se estrenó «MasterChef España»?',2013,'Se estrenó el mismo año que «Frozen».',{s:'rtve'}),
  Y('¿En qué año se estrenó «Física o Química»?',2008,'Se estrenó el mismo año que «Breaking Bad».'),
  Y('¿En qué año se estrenó «Doctor Who» por primera vez?',1963,'Se estrenó el día después del asesinato de Kennedy.'),
  Y('¿En qué año se estrenó el anime de Pokémon en Japón?',1997,'Se estrenó un año después de los primeros juegos.'),
  Y('¿En qué año se estrenó el anime de «Dragon Ball Z»?',1989,'Se estrenó el mismo año que «Los Simpson».'),
  Y('¿En qué año se estrenó el anime de «Oliver y Benji» en Japón?',1983,'Se estrenó un año después del Mundial de España.'),
  Y('¿En qué año se emitió el especial de reencuentro de «Friends»?',2021,'Se emitió en plena era de las plataformas, el año de «El juego del calamar».'),

  // ── Curiosidades ──
  N('¿Cuántos millones de horas se vio «El juego del calamar» en sus primeros 28 días?',1650,'millones de horas','Es la serie más vista de la historia de Netflix en su lanzamiento.',{s:'netflix',ap:true}),
  N('¿Cuántos euros ganó Rafa Castaño con el bote récord de «Pasapalabra»?',2272000,'€','Es el bote más alto de la historia del concurso.',{s:'company'}),
  N('¿Cuántos dólares cobraba cada protagonista de «Friends» por episodio en las últimas temporadas?',1000000,'$','Negociaron juntos y llegaron a una cifra muy redonda.')
]);
