add('Música','britannica',[
  // ── Años ──
  Y('¿En qué año se publicó el álbum «Thriller» de Michael Jackson?',1982,'Salió el año del Mundial de España.'),
  Y('¿En qué año se publicó «All I Want for Christmas Is You» de Mariah Carey?',1994,'Salió el mismo año que se estrenó «Friends».',{s:'billboard'}),
  Y('¿En qué año se convirtió «Gangnam Style» en el primer vídeo de YouTube con 1.000 millones de visitas?',2012,'Fue el año de los Juegos Olímpicos de Londres.',{s:'guinness'}),
  Y('¿En qué año se lanzó Spotify al público?',2008,'Salió el año de la gran crisis financiera.',{s:'spotify'}),
  Y('¿En qué año se formaron los Rolling Stones?',1962,'Se formaron el año de la crisis de los misiles de Cuba.'),
  Y('¿En qué año se publicó «Bohemian Rhapsody» de Queen?',1975,'Salió el año en que murió Franco.'),
  Y('¿En qué año se formaron los Beatles con ese nombre?',1960,'Fue poco antes de que se construyera el Muro de Berlín.'),
  Y('¿En qué año se separaron los Beatles?',1970,'Fue el año siguiente a la llegada del hombre a la Luna.'),
  Y('¿En qué año ganó ABBA Eurovisión con «Waterloo»?',1974,'Fue un año antes de la muerte de Franco.',{s:'eurovision'}),
  Y('¿En qué año se formó Queen?',1970,'Se formó el mismo año en que se separaron los Beatles.'),
  Y('¿En qué año se celebró el concierto benéfico «Live Aid»?',1985,'Fue el año en que se estrenó «Regreso al futuro».'),
  Y('¿En qué año se celebró el festival de Woodstock?',1969,'Fue el verano de la llegada del hombre a la Luna.'),
  Y('¿En qué año se publicó «Smells Like Teen Spirit» de Nirvana?',1991,'Salió el año en que se disolvió la Unión Soviética.'),
  Y('¿En qué año se publicó «Macarena» de Los del Río?',1993,'Salió el año de «Jurassic Park», aunque arrasó en el mundo un poco después.'),
  Y('¿En qué año se publicó «Despacito»?',2017,'Salió el año en que se estrenó «Coco».'),
  Y('¿En qué año se publicó «La Bamba» de Ritchie Valens?',1958,'Salió poco antes de la muerte del cantante en un accidente de avioneta.'),
  Y('¿En qué año se publicó «Like a Virgin» de Madonna?',1984,'Salió el año de «Los Cazafantasmas».'),
  Y('¿En qué año se publicó «Hey Jude» de los Beatles?',1968,'Salió el año del mayo francés.'),
  Y('¿En qué año se publicó «Imagine» de John Lennon?',1971,'Salió poco después de la separación de los Beatles.'),
  Y('¿En qué año se publicó «Yesterday» de los Beatles?',1965,'Salió en plena «beatlemanía», poco después del asesinato de Kennedy.'),
  Y('¿En qué año se publicó el disco «Hotel California» de Eagles?',1976,'Salió el año del bicentenario de Estados Unidos.'),
  Y('¿En qué año se publicó «Wonderwall» de Oasis?',1995,'Salió el año en que se estrenó «Toy Story».'),
  Y('¿En qué año se publicó «...Baby One More Time» de Britney Spears?',1998,'Salió el año del Mundial de Francia.'),
  Y('¿En qué año se publicó «Crazy in Love» de Beyoncé?',2003,'Salió el año de «Buscando a Nemo».'),
  Y('¿En qué año se publicó «Umbrella» de Rihanna?',2007,'Salió el año en que se presentó el primer iPhone.'),
  Y('¿En qué año se publicó «Blinding Lights» de The Weeknd?',2019,'Salió justo antes de la pandemia.'),
  Y('¿En qué año se publicó «Gasolina» de Daddy Yankee?',2004,'Salió el mismo año que se fundó Facebook.'),
  Y('¿En qué año se publicó «Aserejé» de Las Ketchup?',2002,'Salió el año en que llegó el euro a los bolsillos.'),
  Y('¿En qué año se publicó «Bailando» de Enrique Iglesias?',2014,'Salió el año del Mundial de Brasil.'),
  Y('¿En qué año se publicó «Hips Don’t Lie» de Shakira?',2006,'Salió el año del Mundial de Alemania.'),
  Y('¿En qué año se publicó «Livin’ la Vida Loca» de Ricky Martin?',1999,'Salió el año de «Matrix».'),
  Y('¿En qué año se publicó «Mediterráneo» de Joan Manuel Serrat?',1971,'Salió el mismo año que «Imagine».'),
  Y('¿En qué año se publicó «Eye of the Tiger» de Survivor?',1982,'Salió para «Rocky III», el año del Mundial de España.'),
  Y('¿En qué año se publicó «The Final Countdown» de Europe?',1986,'Salió el año del accidente de Chernóbil.'),
  Y('¿En qué año se publicó «Never Gonna Give You Up» de Rick Astley?',1987,'Salió el año de «Dirty Dancing».'),
  Y('¿En qué año se publicó «El mal querer» de Rosalía?',2018,'Salió el año del Mundial de Rusia.'),
  Y('¿En qué año se publicó «Motomami» de Rosalía?',2022,'Salió el año del Mundial de Catar.'),
  Y('¿En qué año se publicó «Un verano sin ti» de Bad Bunny?',2022,'Salió el mismo año que «Motomami».'),
  Y('¿En qué año publicaron Shakira y Bizarrap su famosa «Session»?',2023,'Salió muy recientemente, el año de «Barbie» y «Oppenheimer».'),
  Y('¿En qué año se publicó «Hijo de la luna» de Mecano?',1986,'Salió el año en que España entró en la Comunidad Económica Europea.'),
  Y('¿En qué año se publicó «Corazón partío» de Alejandro Sanz?',1997,'Salió el año de «Titanic».'),
  Y('¿En qué año publicó Estopa su primer disco?',1999,'Salió el mismo año que «Livin’ la Vida Loca».'),
  Y('¿En qué año publicó La Oreja de Van Gogh su primer disco?',1998,'Salió el año del Mundial de Francia.'),
  Y('¿En qué año se publicó «Entre dos tierras» de Héroes del Silencio?',1990,'Salió el año de la reunificación alemana.'),
  Y('¿En qué año se celebró el primer festival de Eurovisión?',1956,'Se celebró en Suiza, en plena posguerra europea, cuando la televisión aún era una novedad.',{s:'eurovision'}),
  Y('¿En qué año ganó Massiel Eurovisión con «La, la, la»?',1968,'Fue el año del mayo francés.',{s:'eurovision'}),
  Y('¿En qué año representó Julio Iglesias a España en Eurovisión?',1970,'Fue el año en que se separaron los Beatles.',{s:'eurovision'}),
  Y('¿En qué año empezó a emitir la cadena MTV?',1981,'Empezó el año del 23-F.'),
  Y('¿En qué año murió Elvis Presley?',1977,'Murió el año en que se estrenó la primera película de Star Wars.'),
  Y('¿En qué año murió Michael Jackson?',2009,'Murió el año en que se estrenó «Avatar».'),
  Y('¿En qué año murió Freddie Mercury?',1991,'Murió el año en que se disolvió la Unión Soviética.'),
  Y('¿En qué año fue asesinado John Lennon?',1980,'Fue el año de los Juegos Olímpicos de Moscú.'),

  // ── Cifras ──
  N('¿Cuántos números 1 consiguieron los Beatles en el Billboard Hot 100?',20,'números 1','Es el récord absoluto de la lista.',{s:'billboard'}),
  N('¿Cuántos números 1 consiguió Elvis Presley en el Billboard Hot 100?',18,'números 1','Tiene algunos menos que los Beatles.',{s:'billboard'}),
  N('¿Cuántos números 1 tiene Mariah Carey en el Billboard Hot 100?',19,'números 1','Es la solista con más números uno, solo por detrás de los Beatles.',{s:'billboard'}),
  N('¿Cuántas semanas estuvo «Despacito» en el número 1 del Billboard Hot 100?',16,'semanas','Igualó el récord que existía en aquel momento.',{s:'billboard'}),
  N('¿Cuántas semanas estuvo «Old Town Road» de Lil Nas X en el número 1 del Billboard Hot 100?',19,'semanas','Batió el récord que tenía «Despacito».',{s:'billboard'}),
  N('¿Cuántos segundos dura «Bohemian Rhapsody» de Queen (versión del álbum)?',355,'segundos','Era demasiado larga para la radio, según la discográfica.'),
  N('¿Cuántos segundos dura «All Too Well (10 Minute Version)» de Taylor Swift?',613,'segundos','Su título casi lo dice, pero dura un poco más.'),
  N('¿Cuántos premios Grammy había ganado Beyoncé tras la gala de 2025?',35,'Grammys','Es la artista con más Grammys de la historia.',{s:'grammy'}),
  N('¿Cuántos Grammy al Álbum del Año ha ganado Taylor Swift, récord absoluto?',4,'premios','Nadie ha ganado más veces ese premio.',{s:'grammy'}),
  N('¿Cuántos Grammy ganó Michael Jackson en una sola noche gracias a «Thriller»?',8,'Grammys','Fue un récord en una única gala.',{s:'grammy'}),
  N('¿Cuántos Grammy ganó Adele en una sola noche con su disco «21»?',6,'Grammys','Arrasó en todas las categorías a las que estaba nominada.',{s:'grammy'}),
  N('¿Cuántos años ha sido Bad Bunny el artista más escuchado del mundo en Spotify?',4,'años','Solo Taylor Swift le ha quitado ese puesto en algunos años.',{s:'spotify'}),
  N('¿Cuántos millones de dólares recaudó el «Eras Tour» de Taylor Swift?',2077,'millones $','Es la gira más taquillera de la historia con muchísima diferencia.',{s:'pollstar',ap:true}),
  N('¿Cuántos conciertos dio Taylor Swift en el «Eras Tour»?',149,'conciertos','Recorrió todos los continentes durante mucho tiempo, con varias noches seguidas en cada ciudad.',{s:'pollstar'}),
  N('¿Cuántos millones de dólares recaudó la gira «Divide» de Ed Sheeran?',776,'millones $','Fue la gira más taquillera hasta que la superó Elton John.',{s:'pollstar',ap:true}),
  N('¿Cuántos millones de dólares recaudó la gira de despedida de Elton John?',939,'millones $','Fue la más taquillera de la historia hasta el «Eras Tour».',{s:'pollstar',ap:true}),
  N('¿Cuántas personas asistieron al festival de Woodstock?',400000,'personas','Fueron muchísimas más de las previstas por los organizadores.',{ap:true}),
  N('¿Cuántas personas asistieron al concierto gratuito de Madonna en la playa de Copacabana?',1600000,'personas','Es uno de los conciertos con más público de la historia.',{ap:true}),
  N('¿Cuántas veces ha ganado España el festival de Eurovisión?',2,'veces','Ambas victorias fueron seguidas.',{s:'eurovision'}),
  N('¿En qué puesto quedó Chanel en Eurovisión con «SloMo»?',3,'º puesto','Fue el mejor resultado de España desde los tiempos de Mocedades y Betty Missiego.',{s:'eurovision'}),
  N('¿Cuántas sinfonías compuso Beethoven?',9,'sinfonías','La última incluye el «Himno de la alegría».'),
  N('¿Cuántos miembros tiene BTS?',7,'miembros','Son bastantes más que en un grupo de rock clásico.'),
  N('¿Cuántas teclas tiene un piano estándar?',88,'teclas','Tiene muchas más blancas que negras.'),
  N('¿Cuántas cuerdas tiene un arpa de concierto?',47,'cuerdas','Tiene muchísimas más que una guitarra.',{ap:true}),
  N('¿Cuántos millones de copias se calcula que ha vendido «Thriller», el disco más vendido de la historia?',70,'millones','Ningún otro disco ha vendido tanto.',{s:'guinness',ap:true}),
  N('¿Cuántos millones de copias se calcula que ha vendido «White Christmas» de Bing Crosby, el single más vendido?',50,'millones','Es el single más vendido de la historia según Guinness.',{s:'guinness',ap:true})
]);
