add('Deporte','britannica',[
  // ── Fútbol: cifras ──
  N('¿Cuántos Balones de Oro ha ganado Leo Messi?',8,'Balones de Oro','Es el récord absoluto del premio.',{s:'ballon'}),
  N('¿Cuántos Balones de Oro ha ganado Cristiano Ronaldo?',5,'Balones de Oro','Tiene menos que Messi.',{s:'ballon'}),
  N('¿Cuántos goles marcó Messi en el año 2012, récord Guinness en un año natural?',91,'goles','Batió un récord que tenía Gerd Müller desde hacía muchísimo tiempo.',{s:'guinness'}),
  N('¿Cuántos goles oficiales marcó Messi con el FC Barcelona?',672,'goles','Es el máximo goleador de la historia del club con mucha diferencia.',{s:'fcb'}),
  N('¿Cuántos títulos ganó Messi con el FC Barcelona?',35,'títulos','Es el jugador con más títulos de la historia del club.',{s:'fcb'}),
  N('¿Cuántos goles marcó Messi en LaLiga, récord de la competición?',474,'goles','Superó con muchísima holgura el récord de Telmo Zarra.',{s:'laliga'}),
  N('¿Cuántos goles marcó Messi en la Champions League?',129,'goles','Está segundo en la historia, por detrás de Cristiano.',{s:'uefa'}),
  N('¿Cuántos goles marcó Cristiano Ronaldo en la Champions League?',140,'goles','Es el máximo goleador de la historia de la competición.',{s:'uefa'}),
  N('¿Cuántos goles oficiales marcó Cristiano Ronaldo con el Real Madrid?',450,'goles','Marcó más goles que partidos jugó en el club.',{s:'rm'}),
  N('¿Cuántos goles oficiales marcó Raúl González con el Real Madrid?',323,'goles','Fue el máximo goleador del club hasta que llegó Cristiano.',{s:'rm'}),
  N('¿Cuántos goles marcó David Villa con la selección española, récord histórico?',59,'goles','Es el máximo goleador de la historia de España.',{s:'rfef'}),
  N('¿Cuántos partidos jugó Sergio Ramos con la selección española, récord histórico?',180,'partidos','Es el jugador con más internacionalidades de España.',{s:'rfef'}),
  N('¿Cuántos partidos jugó Iker Casillas con la selección española?',167,'partidos','Está solo por detrás de Sergio Ramos.',{s:'rfef'}),
  N('¿Cuántos partidos de Mundial ha jugado Messi, récord absoluto?',26,'partidos','Ha jugado muchos Mundiales y llegó lejos en casi todos.',{s:'fifa'}),
  N('¿Cuántos goles marcó Miroslav Klose en Mundiales, récord histórico?',16,'goles','Superó por uno al brasileño Ronaldo.',{s:'fifa'}),
  N('¿Cuántos goles marcó Just Fontaine en un solo Mundial, récord que sigue vigente?',13,'goles','Lo hizo con Francia en el Mundial de Suecia.',{s:'fifa'}),
  N('¿Cuántos millones de euros pagó el Real Madrid por Cristiano Ronaldo?',94,'millones €','Fue el fichaje más caro de la historia en su momento.',{s:'rm',ap:true}),
  N('¿Cuántos millones de euros pagó el PSG por Neymar, el fichaje más caro de la historia?',222,'millones €','Pagó íntegra su cláusula de rescisión.',{s:'fcb'}),
  N('¿Cuántos millones de euros pagó el PSG por Mbappé al Mónaco?',180,'millones €','Es el segundo fichaje más caro de la historia.',{ap:true}),
  N('¿Cuántos millones de euros pagó el Real Madrid por Bale?',101,'millones €','Superó ligeramente lo pagado por Cristiano.',{s:'rm',ap:true}),
  N('¿Cuántos millones de euros pagó el Real Madrid por Zidane?',75,'millones €','Fue el fichaje más caro del mundo en su momento.',{s:'rm',ap:true}),
  N('¿Cuántos millones de euros (en pesetas de la época) pagó el Real Madrid por Figo al Barça?',60,'millones €','Pagó su cláusula, que en pesetas era una cifra redondísima.',{s:'rm',ap:true}),
  N('¿Cuántos millones de euros pagó el Real Madrid por Jude Bellingham, sin variables?',103,'millones €','Pagó algo más que por Bale.',{s:'rm',ap:true}),
  N('¿Cuántas Copas de Europa seguidas ganó el Real Madrid en sus primeras ediciones?',5,'Copas','Ganó todas las primeras ediciones del torneo.',{s:'uefa'}),
  N('¿Cuántas Eurocopas ha ganado la selección española?',4,'Eurocopas','Es la selección con más Eurocopas.',{s:'uefa'}),
  N('¿Cuántos partidos ganó España en la Eurocopa de 2024?',7,'partidos','Los ganó absolutamente todos.',{s:'uefa'}),
  N('¿Cuántos Mundiales ha ganado Brasil?',5,'Mundiales','Es la selección con más Mundiales.',{s:'fifa'}),
  N('¿Cuántos Mundiales ganó Pelé como jugador?',3,'Mundiales','Es el único jugador que lo ha conseguido tantas veces.',{s:'fifa'}),
  N('¿Cuántas selecciones juegan el Mundial de 2026?',48,'selecciones','Es la primera edición con este formato tan ampliado.',{s:'fifa'}),
  N('¿En qué minuto marcó Iniesta el gol que dio a España el Mundial de 2010?',116,'minuto','Fue en la prórroga, poco antes de los penaltis.',{s:'fifa'}),
  N('¿A cuántos metros de la portería está el punto de penalti?',11,'m','Está bastante más cerca que el borde del área grande.',{s:'rules'}),
  N('¿Cuántos metros de ancho mide una portería de fútbol?',7.32,'m','Viene de una medida británica en yardas.',{s:'rules',d:2}),
  N('¿Cuántos metros de alto mide una portería de fútbol?',2.44,'m','Viene de una medida británica en pies.',{s:'rules',d:2}),

  // ── Fútbol: años ──
  Y('¿En qué año se jugó el primer Mundial de fútbol?',1930,'Se jugó en Uruguay, justo después del crac de la bolsa de Nueva York.',{s:'fifa'}),
  Y('¿En qué año marcó Maradona «la mano de Dios»?',1986,'Fue en el Mundial de México.',{s:'fifa'}),
  Y('¿En qué año organizó España un Mundial de fútbol?',1982,'Fue el Mundial de Naranjito.',{s:'fifa'}),
  Y('¿En qué año dio Zidane el famoso cabezazo a Materazzi en la final del Mundial?',2006,'Fue el Mundial de Alemania.',{s:'fifa'}),
  Y('¿En qué año ganó el Real Madrid su primera Copa de Europa?',1956,'Fue en la primera edición del torneo.',{s:'uefa'}),
  Y('¿En qué año ganó el FC Barcelona su primera Copa de Europa?',1992,'Fue en Wembley, el año de los Juegos de Barcelona.',{s:'fcb'}),
  Y('¿En qué año se jugó la primera temporada de la Liga española?',1929,'Fue el año del crac de la bolsa de Nueva York.',{s:'laliga'}),
  Y('¿En qué año se creó la Premier League inglesa?',1992,'Se creó el mismo año que la Champions recibió su nombre actual.'),
  Y('¿En qué año se fundó el Real Madrid?',1902,'Se fundó a comienzos del siglo pasado, poco antes del primer vuelo de los Wright.',{s:'rm'}),
  Y('¿En qué año se fundó el FC Barcelona?',1899,'Se fundó justo antes del cambio de siglo.',{s:'fcb'}),
  Y('¿En qué año se fundó el Atlético de Madrid?',1903,'Se fundó un año después que el Real Madrid.'),
  Y('¿En qué año se fundó el Sevilla FC?',1890,'Es de los clubes más antiguos de España.'),
  Y('¿En qué año se fundó el Athletic Club de Bilbao?',1898,'Se fundó un año antes que el Barça.'),
  Y('¿En qué año se fundó el Valencia CF?',1919,'Se fundó justo después de la Primera Guerra Mundial.'),
  Y('¿En qué año se fundó el Real Betis?',1907,'Se fundó unos años después que el Sevilla.'),
  Y('¿En qué año se fundó el Manchester United (como Newton Heath)?',1878,'Nació como el equipo de unos trabajadores del ferrocarril.'),
  Y('¿En qué año se fundó el Liverpool FC?',1892,'Se fundó unos años antes que el Barça.'),
  Y('¿En qué año se fundó la Juventus?',1897,'Se fundó un par de años antes que el Barça.'),
  Y('¿En qué año se fundó el Bayern de Múnich?',1900,'Se fundó justo con el cambio de siglo.'),
  Y('¿En qué año se fundó Boca Juniors?',1905,'Se fundó unos años después que River Plate.'),
  Y('¿En qué año se inauguró el Camp Nou?',1957,'Se inauguró el año del Sputnik.',{s:'fcb'}),
  Y('¿En qué año se inauguró el estadio Santiago Bernabéu?',1947,'Se inauguró poco después de la Segunda Guerra Mundial.',{s:'rm'}),
  Y('¿En qué año debutó Messi en partido oficial con el Barça?',2004,'Fue el año de los atentados del 11-M.',{s:'fcb'}),
  Y('¿En qué año dejó Messi el FC Barcelona?',2021,'Fue el año de «El juego del calamar».',{s:'fcb'}),
  Y('¿En qué año dejó Cristiano Ronaldo el Real Madrid?',2018,'Fue el año del Mundial de Rusia.',{s:'rm'}),
  Y('¿En qué año ganó Cristiano Ronaldo su primer Balón de Oro?',2008,'Fue el año de la quiebra de Lehman Brothers.',{s:'ballon'}),

  // ── Tenis ──
  N('¿Cuántos Roland Garros ganó Rafa Nadal?',14,'títulos','Ningún tenista ha dominado tanto un mismo torneo.',{s:'rg'}),
  N('¿Cuántos Grand Slams ganó Rafa Nadal?',22,'Grand Slams','Ganó más de la mitad en París.',{s:'atp'}),
  N('¿Cuántos Grand Slams ganó Roger Federer?',20,'Grand Slams','Ganó algunos menos que Nadal.',{s:'atp'}),
  N('¿Cuántos Wimbledon ganó Roger Federer?',8,'títulos','Era su torneo favorito y el que más dominó.',{s:'wimbledon'}),
  N('¿Cuántos Grand Slams individuales ganó Serena Williams?',23,'Grand Slams','Ganó uno de ellos estando embarazada.',{s:'atp'}),
  N('¿Cuántos Grand Slams individuales ganó Steffi Graf?',22,'Grand Slams','Ganó uno menos que Serena Williams.',{s:'atp'}),
  N('¿Cuántos Grand Slams individuales ganó Arantxa Sánchez Vicario?',4,'Grand Slams','Ganó varios Roland Garros y un US Open.',{s:'atp'}),
  N('¿Cuántas medallas de oro olímpicas ganó Rafa Nadal?',2,'oros','Ganó una en individual y otra en dobles.',{s:'olympics'}),
  N('¿Cuántas Copas Davis ha ganado España?',6,'Copas Davis','La primera fue con el cambio de siglo.',{s:'itf'}),
  N('¿Cuántas horas duró el partido de tenis más largo de la historia (Isner–Mahut, Wimbledon 2010)?',11,'horas','Se jugó a lo largo de varios días.',{s:'wimbledon',n:'Exactamente 11 horas y 5 minutos.'}),
  N('¿Cuántos juegos ganó Isner en el último set de su partido histórico contra Mahut?',70,'juegos','En aquel Wimbledon no había desempate en el último set.',{s:'wimbledon',n:'El último set terminó 70-68.'}),
  N('¿Cuántos metros de largo mide una pista de tenis?',23.77,'m','Viene de una medida en pies.',{s:'itf',d:2}),
  Y('¿En qué año se jugó el primer torneo de Wimbledon?',1877,'Es el torneo de tenis más antiguo del mundo.',{s:'wimbledon'}),
  Y('¿En qué año ganó Conchita Martínez Wimbledon?',1994,'Fue el año de «El Rey León».',{s:'wimbledon'}),
  Y('¿En qué año ganó Garbiñe Muguruza Wimbledon?',2017,'Fue el año de la Nintendo Switch.',{s:'wimbledon'}),
  Y('¿En qué año se retiró Rafa Nadal?',2024,'Se despidió en la Copa Davis de Málaga.',{s:'atp'}),
  Y('¿En qué año se retiró Roger Federer?',2022,'Se despidió en la Laver Cup jugando en pareja junto a Nadal, el año del Mundial de Catar.',{s:'atp'}),

  // ── Baloncesto ──
  N('¿Cuántos puntos anotó Kobe Bryant en su mejor partido de la NBA?',81,'puntos','Es la segunda mejor marca de la historia en un partido.',{s:'nba'}),
  N('¿Cuántos puntos anotó Wilt Chamberlain en un solo partido, récord de la NBA?',100,'puntos','Es una cifra muy redonda.',{s:'nba'}),
  N('¿Cuántos anillos de la NBA ganó Michael Jordan?',6,'anillos','Los ganó en rachas separadas, con un retiro para jugar al béisbol en medio.',{s:'nba'}),
  N('¿Cuántos anillos de la NBA ganó Kobe Bryant?',5,'anillos','Ganó uno menos que Jordan.',{s:'nba'}),
  N('¿Cuántos anillos de la NBA ganó Pau Gasol?',2,'anillos','Los ganó con los Lakers, junto a Kobe.',{s:'nba'}),
  N('¿Cuántos puntos de media por partido anotó Michael Jordan en su carrera, récord de la NBA?',30.1,'puntos','Es la media más alta de la historia de la liga.',{s:'nba',d:1}),
  N('¿Cuántos puntos anotó Kareem Abdul-Jabbar en su carrera, récord que duró hasta LeBron?',38387,'puntos','Su récord aguantó muchísimos años, hasta que lo batió LeBron James.',{s:'nba'}),
  N('¿Cuántos Mundiales de baloncesto ha ganado España?',2,'Mundiales','Uno fue en Japón y otro en China.',{s:'feb'}),
  N('¿Cuántos Eurobasket ha ganado España?',4,'Eurobasket','El último fue con un equipo sin grandes estrellas NBA.',{s:'feb'}),
  N('¿Cuántas medallas de plata olímpicas tiene la selección española de baloncesto masculina?',3,'platas','Varias de ellas llegaron perdiendo finales contra Estados Unidos.',{s:'feb'}),
  N('¿Cuántos minutos dura un partido de la NBA sin prórrogas?',48,'minutos','Dura más que un partido FIBA.',{s:'nba'}),
  N('¿Cuántos metros de altura tiene el aro de baloncesto?',3.05,'m','Viene de una medida en pies.',{s:'rules',d:2}),
  N('¿Cuántos metros de largo mide una pista de la NBA?',28.65,'m','Es un poco más larga que una pista FIBA.',{s:'nba',d:2}),
  Y('¿En qué año se fundó la NBA?',1946,'Se fundó justo después de la Segunda Guerra Mundial.',{s:'nba'}),

  // ── Motor ──
  N('¿Cuántos títulos mundiales de Fórmula 1 ganó Michael Schumacher?',7,'títulos','Es el récord, compartido con otro piloto.',{s:'f1'}),
  N('¿Cuántos títulos mundiales de Fórmula 1 tiene Lewis Hamilton?',7,'títulos','Comparte el récord con Michael Schumacher.',{s:'f1'}),
  N('¿Cuántos títulos mundiales de Fórmula 1 ganó Ayrton Senna?',3,'títulos','Ganó menos que Prost, su gran rival.',{s:'f1'}),
  N('¿Cuántos títulos mundiales de Fórmula 1 tiene Max Verstappen?',4,'títulos','Los ganó de forma consecutiva.',{s:'f1'}),
  N('¿Cuántas carreras de Fórmula 1 ha ganado Fernando Alonso?',32,'victorias','Lleva muchos años sin ganar, pero ganó muchas en su época dorada.',{s:'f1'}),
  N('¿Cuántas vueltas tiene el Gran Premio de Mónaco de Fórmula 1?',78,'vueltas','El circuito es muy corto, así que hay que dar muchas.',{s:'f1'}),
  N('¿Cuántos títulos mundiales de MotoGP (categoría reina) tiene Marc Márquez?',7,'títulos','Volvió a ganar tras años de lesiones.',{s:'motogp'}),
  N('¿Cuántos títulos mundiales de motociclismo ganó Valentino Rossi en total?',9,'títulos','Ganó en varias cilindradas.',{s:'motogp'}),
  N('¿Cuántos títulos mundiales de motociclismo ganó Ángel Nieto?',13,'títulos','Por superstición, nunca decía la cifra exacta: siempre la contaba como una suma.',{s:'motogp'}),
  Y('¿En qué año ganó Fernando Alonso su primer Mundial de Fórmula 1?',2005,'Fue el año en que se fundó YouTube.',{s:'f1'}),
  Y('¿En qué año ganó Fernando Alonso su primera carrera de Fórmula 1?',2003,'Fue en Hungría, el año de «Buscando a Nemo».',{s:'f1'}),
  Y('¿En qué año se disputó el primer Mundial de Fórmula 1?',1950,'Fue a mediados del siglo pasado, después de la Segunda Guerra Mundial.',{s:'f1'}),
  Y('¿En qué año ganó Carlos Sainz su primera carrera de Fórmula 1?',2022,'Fue en Silverstone, el año del Mundial de Catar.',{s:'f1'}),

  // ── Olimpismo y atletismo ──
  N('¿En cuántos segundos corrió Usain Bolt los 100 metros en su récord del mundo?',9.58,'s','Nadie se ha acercado a esa marca.',{s:'athletics',d:2}),
  N('¿En cuántos segundos corrió Usain Bolt los 200 metros en su récord del mundo?',19.19,'s','Lo hizo en el mismo Mundial de Berlín en que batió su otro récord.',{s:'athletics',d:2}),
  N('¿En cuántos segundos corrió Florence Griffith-Joyner los 100 metros en su récord del mundo?',10.49,'s','Es un récord que sigue vigente desde hace muchísimo tiempo.',{s:'athletics',d:2}),
  N('¿Cuántos metros saltó Javier Sotomayor en su récord del mundo de salto de altura?',2.45,'m','Sigue siendo récord del mundo.',{s:'athletics',d:2}),
  N('¿Cuántos metros saltó Mike Powell en su récord del mundo de salto de longitud?',8.95,'m','Batió el récord de Bob Beamon, que parecía imbatible.',{s:'athletics',d:2}),
  N('¿Cuántas medallas olímpicas ganó Michael Phelps en total?',28,'medallas','Es el deportista con más medallas olímpicas de la historia.',{s:'olympics'}),
  N('¿Cuántas medallas de oro olímpicas ganó Michael Phelps?',23,'oros','Ganó muchísimas más de oro que de plata y bronce juntas.',{s:'olympics'}),
  N('¿Cuántas medallas de oro olímpicas tiene Usain Bolt?',8,'oros','Le quitaron una por el dopaje de un compañero de relevo.',{s:'olympics'}),
  N('¿Cuántas medallas ganó España en los Juegos Olímpicos de Barcelona 92?',22,'medallas','Fue su mejor actuación histórica.',{s:'coe'}),
  N('¿Cuántas medallas de oro ganó España en Barcelona 92?',13,'oros','Fue una cifra que nunca se ha vuelto a igualar.',{s:'coe'}),
  N('¿Cuántas medallas ganó España en los Juegos Olímpicos de París 2024?',18,'medallas','Fue una de sus mejores actuaciones fuera de casa.',{s:'coe'}),
  N('¿Cuántos metros mide exactamente una maratón?',42195,'m','La distancia se fijó en unos Juegos de Londres para que acabara frente al palco real.',{s:'athletics'}),
  Y('¿En qué año se celebraron los primeros Juegos Olímpicos modernos?',1896,'Se celebraron en Atenas, en homenaje a los Juegos de la antigua Grecia.',{s:'olympics'}),
  Y('¿En qué año logró Nadia Comaneci el primer «10» de la gimnasia olímpica?',1976,'Fue en los Juegos de Montreal.',{s:'olympics'}),

  // ── Ciclismo ──
  N('¿Cuántas etapas tiene el Tour de Francia?',21,'etapas','Dura casi un mes, con un par de días de descanso.',{s:'letour'}),
  N('¿Cuántos Tours de Francia ganó Miguel Induráin?',5,'Tours','Los ganó todos seguidos.',{s:'letour'}),
  N('¿Cuántos Tours de Francia tiene oficialmente Alberto Contador?',2,'Tours','Le retiraron uno por dopaje.',{s:'letour'}),
  Y('¿En qué año ganó Pedro Delgado el Tour de Francia?',1988,'Fue el año de los Juegos de Seúl.',{s:'letour'}),
  Y('¿En qué año ganó Carlos Sastre el Tour de Francia?',2008,'Fue el año de los Juegos de Pekín.',{s:'letour'}),
  Y('¿En qué año se corrió el primer Tour de Francia?',1903,'Fue el mismo año del primer vuelo de los hermanos Wright.',{s:'letour'}),
  Y('¿En qué año se corrió la primera Vuelta a España?',1935,'Fue poco antes de la Guerra Civil.'),

  // ── Otros deportes ──
  N('¿Cuántos Masters de Augusta ganó Severiano Ballesteros?',2,'chaquetas verdes','Fue el primer europeo en ganarlo.',{s:'pga'}),
  N('¿Cuántos torneos «major» de golf ha ganado Tiger Woods?',15,'majors','Solo Jack Nicklaus ha ganado más.',{s:'pga'}),
  N('¿Cuántas Super Bowls ganó Tom Brady?',7,'Super Bowls','Ganó más que cualquier franquicia de la NFL.',{s:'nfl'}),
  Y('¿En qué año ganó Jon Rahm el Masters de Augusta?',2023,'Fue el año de «Barbie» y «Oppenheimer».',{s:'pga'}),
  Y('¿En qué año se jugó la primera Super Bowl?',1967,'Fue el año del primer trasplante de corazón.',{s:'nfl'}),
  Y('¿En qué año ganó Deep Blue al campeón del mundo de ajedrez Kasparov?',1997,'Fue el año de «Titanic».'),
  N('¿Cuántos minutos dura un partido de balonmano?',60,'minutos','Dura menos que uno de fútbol.',{s:'rules'}),
  N('¿Cuántos minutos dura un partido de rugby?',80,'minutos','Dura menos que uno de fútbol, pero más que uno de balonmano.',{s:'rules'}),
  N('¿Cuántos litros de agua caben en una piscina olímpica?',2500000,'litros','Es una cantidad enorme, de muchos camiones cisterna.',{s:'aquatics',ap:true})
]);
