add('Marcas','company',[
  // ── Años de origen ──
  Y('¿En qué año se inventó la Coca-Cola?',1886,'Se inventó en una farmacia de Atlanta, el mismo año que se inauguró la Estatua de la Libertad.',{s:'cocacola'}),
  Y('¿En qué año se inventó la bebida que después se llamaría Pepsi?',1893,'Se inventó unos años después que la Coca-Cola, también en una farmacia.'),
  Y('¿En qué año salió la Coca-Cola Light (Diet Coke)?',1982,'Salió el año del Mundial de España.',{s:'cocacola'}),
  Y('¿En qué año salió la Coca-Cola Zero?',2005,'Salió el año en que se fundó YouTube.',{s:'cocacola'}),
  Y('¿En qué año se creó Fanta?',1940,'Se creó en Alemania durante la Segunda Guerra Mundial.'),
  Y('¿En qué año se creó Red Bull?',1987,'Se creó el año de «Dirty Dancing».'),
  Y('¿En qué año se creó la Nutella?',1964,'Se creó el mismo año que Mafalda.',{s:'ferrero'}),
  Y('¿En qué año se creó la Nocilla?',1967,'Se creó unos años después que la Nutella.'),
  Y('¿En qué año se creó el Cola Cao?',1946,'Se creó justo después de la Segunda Guerra Mundial.'),
  Y('¿En qué año salió el Kinder Sorpresa?',1974,'Salió el mismo año que el cubo de Rubik.',{s:'ferrero'}),
  Y('¿En qué año salieron los Ferrero Rocher?',1982,'Salieron el año del Mundial de España.',{s:'ferrero'}),
  Y('¿En qué año salieron los M&M’s?',1941,'Se pensaron para los soldados de la Segunda Guerra Mundial.'),
  Y('¿En qué año salieron las galletas Oreo?',1912,'Salieron el mismo año en que se hundió el Titanic.'),
  Y('¿En qué año nació Chupa Chups?',1958,'Nació el mismo año que se patentó el ladrillo de LEGO.',{s:'chupachups'}),
  Y('¿En qué año diseñó Dalí el logotipo de Chupa Chups?',1969,'Fue el año de la llegada del hombre a la Luna.',{s:'chupachups'}),
  Y('¿En qué año se creó el Big Mac?',1967,'Se creó el año del primer trasplante de corazón.',{s:'mcdonalds'}),
  Y('¿En qué año abrieron los hermanos McDonald su primer restaurante?',1940,'Fue en California, en plena Segunda Guerra Mundial en Europa.',{s:'mcdonalds'}),
  Y('¿En qué año se fundó Starbucks?',1971,'Se fundó en Seattle, el año de «Imagine».'),
  Y('¿En qué año se fundó Telepizza?',1987,'Se fundó en Madrid, el mismo año que nació Red Bull.'),
  Y('¿En qué año se fundó Danone, en Barcelona?',1919,'Se fundó justo después de la Primera Guerra Mundial.'),
  Y('¿En qué año se fundó Mahou?',1890,'Se fundó en Madrid poco después de que naciera la Coca-Cola.'),
  Y('¿En qué año se fundó Estrella Galicia?',1906,'Se fundó en A Coruña a comienzos del siglo pasado.'),
  Y('¿En qué año se fundó Bimbo, en México?',1945,'Se fundó el año en que terminó la Segunda Guerra Mundial.'),
  Y('¿En qué año se fundó LEGO?',1932,'Se fundó en Dinamarca durante la Gran Depresión.',{s:'lego'}),
  Y('¿En qué año se patentó el ladrillo de LEGO tal y como lo conocemos?',1958,'Fue el mismo año que nació Chupa Chups.',{s:'lego'}),
  Y('¿En qué año salió la primera minifigura de LEGO?',1978,'Salió el año en que se aprobó la Constitución española.',{s:'lego'}),
  Y('¿En qué año salió a la venta la primera Barbie?',1959,'Salió el año en que triunfó la Revolución cubana.',{s:'mattel'}),
  Y('¿En qué año salió Playmobil?',1974,'Salió el mismo año que el Kinder Sorpresa.'),
  Y('¿En qué año salió la muñeca Nancy de Famosa?',1968,'Salió el año en que Massiel ganó Eurovisión.'),
  Y('¿En qué año salió el Furby?',1998,'Salió el año del Mundial de Francia.',{s:'hasbro'}),
  Y('¿En qué año se creó Hello Kitty?',1974,'Se creó el mismo año que Playmobil.'),
  Y('¿En qué año se inventó el cubo de Rubik?',1974,'Se inventó en Hungría, el mismo año que el Kinder Sorpresa.'),
  Y('¿En qué año salió el Monopoly comercializado por Parker Brothers?',1935,'Salió en plena Gran Depresión.',{s:'hasbro'}),
  Y('¿En qué año salió el Trivial Pursuit?',1981,'Salió el año del 23-F.',{s:'hasbro'}),
  Y('¿En qué año salió el Cluedo?',1949,'Salió poco después de la Segunda Guerra Mundial.',{s:'hasbro'}),
  Y('¿En qué año salieron los pósits (Post-it)?',1980,'Salieron el año en que fue asesinado John Lennon.'),
  Y('¿En qué año salió el bolígrafo BIC Cristal?',1950,'Salió a mediados del siglo pasado, en Francia.'),
  Y('¿En qué año salieron las zapatillas Converse All Star?',1917,'Salieron el año de la Revolución rusa.'),
  Y('¿En qué año salieron las gafas Ray-Ban?',1937,'Salieron para los pilotos, poco antes de la Segunda Guerra Mundial.'),
  Y('¿En qué año se fundó Rolex?',1905,'Se fundó en Londres, el año de la relatividad de Einstein.'),
  Y('¿En qué año se fundó Louis Vuitton?',1854,'Se fundó en París como fabricante de baúles, cuando aún se viajaba en diligencia.'),
  Y('¿En qué año salió el perfume Chanel nº 5?',1921,'Salió poco después de la Primera Guerra Mundial.'),
  Y('¿En qué año patentó Levi Strauss los vaqueros con remaches?',1873,'Fue en California, pocos años después de inaugurarse el canal de Suez.'),
  Y('¿En qué año adoptó la marca el nombre de Nike?',1971,'Fue el mismo año que se fundó Starbucks.'),
  Y('¿En qué año se fundó Adidas?',1949,'Se fundó tras la pelea entre los hermanos Dassler; el otro creó Puma.'),
  Y('¿En qué año se fundó Puma?',1948,'Se fundó un año antes que Adidas, tras la pelea entre los hermanos Dassler.'),
  Y('¿En qué año se fundó IKEA?',1943,'Se fundó en Suecia durante la Segunda Guerra Mundial.',{s:'ikea'}),
  Y('¿En qué año abrió la primera tienda de Zara?',1975,'Abrió en A Coruña el año en que murió Franco.',{s:'inditex'}),
  Y('¿En qué año se fundó Mercadona?',1977,'Se fundó en Valencia el año de las primeras elecciones democráticas.',{s:'mercadona'}),
  Y('¿En qué año se fundó Mango?',1984,'Se fundó en Barcelona el año de «Terminator».'),
  Y('¿En qué año se fundó H&M?',1947,'Se fundó en Suecia poco después de la Segunda Guerra Mundial.'),
  Y('¿En qué año se fundó Primark?',1969,'Se fundó en Dublín el año de la llegada a la Luna.'),
  Y('¿En qué año adoptó El Corte Inglés su nombre actual?',1940,'Fue poco después de la Guerra Civil.'),
  Y('¿En qué año se fundó Samsung?',1938,'Se fundó en Corea vendiendo comida y pescado seco.'),
  Y('¿En qué año se fundó Sony?',1946,'Se fundó en Japón justo después de la Segunda Guerra Mundial.'),
  Y('¿En qué año se fundó The Walt Disney Company?',1923,'Se fundó el año en que se instaló el letrero de Hollywood.',{s:'disney'}),
  Y('¿En qué año se fundó Warner Bros.?',1923,'Se fundó el mismo año que Disney.'),
  Y('¿En qué año se fundó Ford Motor Company?',1903,'Se fundó el año del primer vuelo de los hermanos Wright.',{s:'ford'}),
  Y('¿En qué año salió el Ford Model T?',1908,'Salió pocos años después de fundarse Ford.',{s:'ford'}),
  Y('¿En qué año se fundó Harley-Davidson?',1903,'Se fundó el mismo año que Ford.'),
  Y('¿En qué año se fundó SEAT?',1950,'Se fundó en plena posguerra española.'),
  Y('¿En qué año se fabricó el primer coche con el nombre Ferrari?',1947,'Fue poco después de la Segunda Guerra Mundial.'),
  Y('¿En qué año se fundó Toyota Motor?',1937,'Se fundó poco antes de la Segunda Guerra Mundial; antes hacía telares.'),
  Y('¿En qué año salió el Mini original?',1959,'Salió el mismo año que la Barbie.'),
  Y('¿En qué año se fabricó el último Volkswagen Escarabajo clásico?',2003,'Se fabricó en México, el año del primer «Call of Duty».',{s:'vw'}),

  // ── Cifras ──
  N('¿Cuántos millones de unidades se fabricaron del Ford Model T?',15,'millones','Fue el coche que motorizó Estados Unidos.',{s:'ford',ap:true}),
  N('¿Cuántos dólares costaba el Ford Model T cuando salió?',850,'$','Era barato para la época y cada año bajaba de precio.',{s:'ford'}),
  N('¿Cuántos millones de unidades se fabricaron del Volkswagen Escarabajo clásico?',21.5,'millones','Superó al Ford Model T.',{s:'vw',d:1,ap:true}),
  N('¿Cuántas Coca-Colas se vendían de media al día durante su primer año?',9,'vasos','Fueron poquísimas: se vendía en una sola farmacia.',{s:'cocacola'}),
  N('¿Cuántas casillas tiene el tablero del Monopoly?',40,'casillas','Cada lado tiene el mismo número de casillas, contando las esquinas.',{s:'hasbro'}),
  N('¿Cuántas fichas tiene un juego de Scrabble?',100,'fichas','Es una cifra muy redonda.',{s:'hasbro'}),
  N('¿Cuántas categorías de preguntas tiene el Trivial Pursuit clásico?',6,'categorías','Cada una tiene su color de quesito.',{s:'hasbro'}),
  N('¿Cuántas fichas tiene un dominó clásico?',28,'fichas','Hay una ficha por cada combinación posible de puntos.',{s:'rules'}),
  N('¿Cuántas cartas tiene una baraja de póker sin comodines?',52,'cartas','Todos los palos tienen el mismo número de cartas.',{s:'rules'}),
  N('¿Cuántas piezas tiene en total un juego de ajedrez?',32,'piezas','Cada jugador empieza con la mitad.',{s:'rules'}),
  N('¿Cuántas fichas tiene un parchís para cuatro jugadores?',16,'fichas','Cada jugador tiene las mismas.',{s:'rules'}),
  N('¿Cuántos puntos suman todas las caras de un dado?',21,'puntos','Las caras opuestas siempre suman lo mismo.',{s:'rules'})
]);
