add('Mundo','britannica',[
  // ── Monumentos ──
  N('¿Cuántos metros mide la Torre Eiffel?',330,'m','Fue el edificio más alto del mundo durante años.',{s:'eiffel'}),
  N('¿Cuántas toneladas de pintura se usan cada vez que se pinta la Torre Eiffel?',60,'toneladas','Se pinta a mano cada pocos años.',{s:'eiffel'}),
  N('¿Cuántas toneladas pesa la Torre Eiffel?',10100,'toneladas','Pesa muchísimo, aunque menos de lo que parece para su tamaño.',{s:'eiffel',ap:true}),
  N('¿Cuántos remaches tiene la Torre Eiffel?',2500000,'remaches','Son muchísimos, colocados a mano.',{s:'eiffel',ap:true}),
  N('¿Cuántos meses se tardó en construir la Torre Eiffel?',26,'meses','Se construyó en un tiempo récord para la Exposición Universal.',{s:'eiffel'}),
  N('¿Cuántos metros mide la Estatua de la Libertad desde el suelo hasta la antorcha?',93,'m','El pedestal mide casi lo mismo que la propia estatua.',{s:'nps'}),
  N('¿Cuántas ventanas tiene la corona de la Estatua de la Libertad?',25,'ventanas','Representan las piedras preciosas de la tierra.',{s:'nps'}),
  N('¿Cuántos metros medía originalmente la Gran Pirámide de Guiza?',147,'m','Fue la construcción más alta del mundo durante muchísimo tiempo.',{ap:true}),
  N('¿Cuántos centímetros de alto mide La Gioconda?',77,'cm','Es mucho más pequeña de lo que la gente espera.',{s:'louvre'}),
  N('¿Cuántos centímetros de ancho mide el «Guernica» de Picasso?',777,'cm','Ocupa una pared entera del museo.',{s:'reinasofia',ap:true}),
  N('¿Cuántos metros mide el Cristo Redentor de Río de Janeiro sin contar el pedestal?',30,'m','Sus brazos abiertos miden casi lo mismo que su altura.'),
  N('¿Cuántos años se tardó en terminar la Torre de Pisa?',199,'años','Se empezó a inclinar durante la construcción, que duró muchísimo.',{ap:true}),
  N('¿Cuántos grados está inclinada la Torre de Pisa?',4,'grados','Tras la restauración se corrigió un poco la inclinación.',{ap:true}),
  N('¿Cuántas torres tendrá la Sagrada Familia cuando esté terminada?',18,'torres','Representan a los apóstoles, los evangelistas, la Virgen y Jesucristo.',{s:'sagrada'}),
  N('¿Cuántos metros medirá la torre de Jesucristo de la Sagrada Familia?',172.5,'m','Será la iglesia más alta del mundo, pero algo más baja que Montjuïc.',{s:'sagrada',d:1}),
  N('¿Cuántos metros mide la torre del Big Ben?',96,'m','Es más baja que la Torre Eiffel, pero muy alta para su época.',{s:'parliament',ap:true}),
  N('¿Cuántos espectadores cabían aproximadamente en el Coliseo romano?',50000,'espectadores','Cabía más gente que en muchos estadios de fútbol actuales.',{ap:true}),
  N('¿Cuántos años se tardó aproximadamente en construir el Taj Mahal?',22,'años','Fue una obra enorme encargada por un emperador en memoria de su esposa.',{ap:true}),
  N('¿Cuántos metros mide el puente Golden Gate de longitud total?',2737,'m','Fue el puente colgante más largo del mundo cuando se inauguró.',{s:'ggb'}),
  N('¿Cuántas plantas tiene el Empire State Building?',102,'plantas','Fue el edificio más alto del mundo durante muchísimos años.',{s:'esb'}),
  N('¿Cuántos días se tardó en construir el Empire State Building?',410,'días','Se construyó en poco más de un año, a una velocidad increíble.',{s:'esb'}),
  N('¿Cuántas plantas tenía cada una de las Torres Gemelas?',110,'plantas','Superaban en plantas al Empire State.'),
  N('¿Cuántas plantas tiene el Burj Khalifa, el edificio más alto del mundo?',163,'plantas','Tiene muchísimas más que el Empire State.',{s:'burj'}),
  N('¿Cuántos metros mide el Burj Khalifa?',828,'m','Es muchísimo más alto que la Torre Eiffel.',{s:'burj'}),
  N('¿Cuántos kilómetros mide la Gran Muralla China contando todos sus tramos?',21196,'km','Es más larga que la distancia de un polo al otro de la Tierra.',{s:'unesco',ap:true}),
  N('¿Cuántos metros sobre el nivel del mar está Machu Picchu?',2430,'m','Está alto, pero mucho más bajo que Cuzco.',{ap:true}),
  N('¿Cuántos kilómetros mide el Eurotúnel?',50,'km','Es una cifra muy redonda, y buena parte va bajo el mar.',{ap:true}),
  N('¿Cuántos kilómetros recorre el Transiberiano entre Moscú y Vladivostok?',9289,'km','Es la línea de tren más larga del mundo.',{ap:true}),
  Y('¿En qué año se inauguró la Torre Eiffel?',1889,'Se inauguró para la Exposición Universal que celebraba un aniversario redondo de la Revolución francesa.',{s:'eiffel'}),
  Y('¿En qué año se inauguró la Estatua de la Libertad?',1886,'Se inauguró el mismo año en que se inventó la Coca-Cola.',{s:'nps'}),
  Y('¿En qué año se empezó a construir la Sagrada Familia?',1882,'Se empezó antes de que Gaudí se hiciera cargo del proyecto.',{s:'sagrada'}),
  Y('¿En qué año se inauguró el puente Golden Gate?',1937,'Se inauguró el año del bombardeo de Guernica.',{s:'ggb'}),
  Y('¿En qué año se inauguró el Empire State Building?',1931,'Se inauguró en plena Gran Depresión.',{s:'esb'}),
  Y('¿En qué año se inauguró el Burj Khalifa?',2010,'Se inauguró el año del Mundial de Sudáfrica.',{s:'burj'}),
  Y('¿En qué año se instaló el reloj del Big Ben?',1859,'Se instaló el mismo año en que Darwin publicó «El origen de las especies».',{s:'parliament'}),
  Y('¿En qué año se inauguró el metro de Londres, el primero del mundo?',1863,'Se inauguró en plena época victoriana, durante la guerra de Secesión estadounidense.',{s:'metro'}),
  Y('¿En qué año se inauguró el metro de Madrid?',1919,'Lo inauguró Alfonso XIII justo después de la Primera Guerra Mundial.',{s:'metro'}),
  Y('¿En qué año se inauguró el metro de Barcelona?',1924,'Se inauguró unos años después que el de Madrid.',{s:'metro'}),
  Y('¿En qué año se inauguró el metro de París?',1900,'Se inauguró para la Exposición Universal del cambio de siglo.',{s:'metro'}),
  Y('¿En qué año se inauguró el metro de Nueva York?',1904,'Se inauguró a comienzos del siglo pasado, poco después que el de París.',{s:'metro'}),
  Y('¿En qué año se inauguró la primera línea de AVE, entre Madrid y Sevilla?',1992,'Se inauguró para la Expo de Sevilla.',{s:'adif'}),
  Y('¿En qué año hizo su primer vuelo el Boeing 747, el «Jumbo»?',1969,'Fue el año de la llegada del hombre a la Luna.'),

  // ── Geografía ──
  N('¿Cuántos metros mide el Everest según la medición oficial de 2020?',8849,'m','Es la montaña más alta del mundo.',{s:'nepal'}),
  N('¿Cuántos metros mide el Teide, el pico más alto de España?',3715,'m','Es más alto que cualquier montaña de la Península.',{s:'ign'}),
  N('¿Cuántos metros mide el Mulhacén, el pico más alto de la Península?',3479,'m','Está en Sierra Nevada, algo más bajo que el Teide.',{s:'ign'}),
  N('¿Cuántos metros mide el Aneto, el pico más alto de los Pirineos?',3404,'m','Es algo más bajo que el Mulhacén.',{s:'ign'}),
  N('¿Cuántos metros mide el Kilimanjaro?',5895,'m','Es la montaña más alta de África.'),
  N('¿Cuántos metros mide el Aconcagua?',6961,'m','Es la montaña más alta de América.'),
  N('¿Cuántos metros mide el K2, la segunda montaña más alta del mundo?',8611,'m','Es algo más baja que el Everest, pero mucho más peligrosa.'),
  N('¿Cuántos kilómetros cuadrados mide España?',506000,'km²','Es uno de los países más grandes de Europa occidental.',{s:'ine',ap:true}),
  N('¿Cuántos millones de kilómetros cuadrados mide Rusia?',17.1,'millones de km²','Es el país más grande del mundo con muchísima diferencia.',{d:1,ap:true}),
  N('¿Cuántas hectáreas mide el Vaticano, el país más pequeño del mundo?',44,'hectáreas','Es más pequeño que muchos parques urbanos.',{s:'vatican',ap:true}),
  N('¿Cuántos millones de kilómetros cuadrados mide el desierto del Sahara?',9,'millones de km²','Es casi tan grande como Estados Unidos.',{ap:true}),
  N('¿Cuántos millones de habitantes tiene España, según el INE en 2025?',49,'millones','Ha crecido gracias a la inmigración.',{s:'ine',ap:true}),
  N('¿Cuántos países hay en África?',54,'países','Es el continente con más países.',{s:'un'}),
  N('¿Cuántos idiomas oficiales tiene la ONU?',6,'idiomas','El español es uno de ellos.',{s:'un'}),
  N('¿Cuántos husos horarios tiene Rusia?',11,'husos horarios','Cuando en Moscú se cena, en el otro extremo ya es de madrugada.'),
  N('¿Cuántos husos horarios tiene Francia contando sus territorios de ultramar, récord mundial?',12,'husos horarios','Tiene islas repartidas por todos los océanos.'),
  N('¿Cuántas islas tiene Japón según el recuento oficial de 2023?',14125,'islas','Son muchísimas más de las que se creía antes del nuevo recuento.',{ap:true}),
  N('¿Cuántas islas forman la ciudad de Venecia?',118,'islas','Están unidas por muchísimos puentes.',{ap:true}),
  N('¿Cuántas estrellas tiene la bandera de la Unión Europea?',12,'estrellas','No depende del número de países miembros.',{s:'eu'}),
  N('¿Cuántas franjas tiene la bandera de Estados Unidos?',13,'franjas','Representan las colonias originales.'),
  N('¿Cuántos kilómetros mide la circunferencia de la Tierra en el ecuador?',40075,'km','Una vuelta completa al mundo por el ecuador.',{s:'nasa'}),

  // ── Espacio ──
  N('¿Cuántos kilómetros hay de media entre la Tierra y la Luna?',384400,'km','Cabrían todos los planetas del sistema solar en ese hueco.',{s:'nasa'}),
  N('¿Cuántos millones de kilómetros hay de media entre la Tierra y el Sol?',150,'millones de km','La luz tarda unos minutos en recorrerlos.',{s:'nasa',ap:true}),
  N('¿Cuántos segundos tarda la luz del Sol en llegar a la Tierra?',499,'segundos','Si el Sol se apagara, tardaríamos unos minutos en enterarnos.',{s:'nasa',ap:true}),
  N('¿Cuántos kilómetros por segundo recorre la luz en el vacío?',299792,'km/s','Daría varias vueltas a la Tierra en un segundo.',{s:'nasa'}),
  N('¿Cuántos kilómetros de diámetro tiene la Luna?',3474,'km','Es bastante más pequeña que la Tierra, pero grande para ser una luna.',{s:'nasa'}),
  N('¿Cuántas vueltas a la Tierra da la Estación Espacial Internacional cada día?',16,'vueltas','Los astronautas ven muchísimos amaneceres cada día.',{s:'nasa',ap:true}),
  N('¿A cuántos kilómetros de altura orbita la Estación Espacial Internacional?',400,'km','Está mucho más cerca de lo que la gente cree.',{s:'nasa',ap:true}),
  N('¿Cuántos millones de años tiene el Sol aproximadamente?',4600,'millones de años','Está más o menos a la mitad de su vida.',{s:'nasa',ap:true}),
  N('¿Cada cuántos años pasa el cometa Halley cerca de la Tierra?',76,'años','Mucha gente solo lo ve una vez en la vida.',{s:'nasa',ap:true}),
  N('¿A cuántos kilómetros por hora gira la Tierra en el ecuador?',1670,'km/h','Gira más rápido que un avión comercial.',{s:'nasa',ap:true}),
  Y('¿En qué año volverá a verse el cometa Halley?',2061,'Será dentro de bastantes años.',{s:'nasa'}),

  // ── Cuerpo humano ──
  N('¿Cuántos huesos tiene el cuerpo humano adulto?',206,'huesos','Al nacer tenemos más, pero algunos se fusionan.',{s:'nih'}),
  N('¿Cuántos huesos tiene cada pie humano?',26,'huesos','Los pies concentran una buena parte de los huesos del cuerpo.',{s:'nih'}),
  N('¿Cuántos huesos tiene cada mano humana?',27,'huesos','Tiene uno más que el pie.',{s:'nih'}),
  N('¿Cuántos dientes tiene un adulto con las muelas del juicio?',32,'dientes','Los niños tienen bastantes menos.',{s:'nih'}),
  N('¿Cuántos dientes de leche tiene un niño?',20,'dientes','Son bastantes menos que los definitivos.',{s:'nih'}),
  N('¿Cuántos cromosomas tiene una célula humana?',46,'cromosomas','Van por parejas: la mitad viene de cada progenitor.',{s:'nih'}),
  N('¿Cuántos litros de sangre tiene un adulto aproximadamente?',5,'litros','Es más o menos lo que cabe en una garrafa grande de agua.',{s:'nih',ap:true}),
  N('¿Cuántos gramos pesa aproximadamente el cerebro de un adulto?',1400,'g','Pesa más o menos como un paquete grande de azúcar y medio.',{s:'nih',ap:true}),
  N('¿Cuántas veces late el corazón al día aproximadamente?',100000,'latidos','Late sin parar, más de una vez por segundo.',{s:'nih',ap:true}),

  // ── Animales ──
  N('¿Cuántos meses dura el embarazo de una elefanta?',22,'meses','Es el embarazo más largo de todos los mamíferos terrestres.',{s:'smithsonian'}),
  N('¿Cuántas vértebras tiene el cuello de una jirafa?',7,'vértebras','Tiene las mismas que un ser humano, pero mucho más largas.',{s:'smithsonian'}),
  N('¿Cuántos corazones tiene un pulpo?',3,'corazones','Tiene más de uno.',{s:'nhm'}),
  N('¿Cuántos ojos tiene una abeja?',5,'ojos','Además de los ojos grandes que se ven, tiene otros pequeños en lo alto de la cabeza.',{s:'nhm'}),
  N('¿Cuántos gramos pesa un oso panda al nacer?',100,'g','Es diminuto: pesa como una tableta de chocolate.',{s:'smithsonian',ap:true})
]);
